gCurrentLanguage = "English"

strings = 
{
    ["English"] = 
    { 
        -- gw2.lua
        startStop                       = "StartStop",
        doPulse                         = "Pulse(Debug)",
        pulseTime                       = "Pulse Time (ms)",
        enableLog                       = "Enable Log",
        task                            = "Task",
        state                           = "State",
        effect                          = "Effect",
        autoStartBot                    = "AutoStartBot",
        combatMovement                  = "EnableCombatMovement",
        enableEvents                    = "EnableEvents",
        enableRepair                    = "EnableRepair",
        ignoreLevelMarker               = "IgnoreLevelMarker",
        wpVendor                        = "UseWPForVendor",
        wpEvents                        = "UseWPForEvents",
        enableUnstuck                   = "EnableUnstuck",
        unstuckCount                    = "UnstuckExitCount",
        eventTimeout                    = "EventTimeout",
        blacklistEvent                  = "BlacklistEvent",
        prioEvent                       = "Events>Aggro",
        prioRevive                      = "Revive>Aggro",
        vendorRarity                    = "MaxItemSellRarity",
        sellWeapon                      = "SellWeapons",
        sellArmor                       = "SellArmor",
        sellTrinket                     = "SellTrinkets",
        sellUpgrade                     = "SellUpgradeComponents",
        sellCrafting                    = "SellCraftingMats",
        sellTrophy                      = "SellTrophies",
        enableGather                    = "EnableGathering",
        buyTools                        = "BuyGatheringTools",
        buyBestTool                     = "BuyBestTool",
        toolRarity                      = "ToolRarity",
        toolStock                       = "ToolStock",
        enableSalvage                   = "EnableSalvaging",
        buyKits                         = "BuySalvageKits",
        buyBestKit                      = "BuyBestKit",
        kitRarity                       = "KitRarity",
        kitStock                        = "KitStock",
        salvageTrophy                   = "SalvageTrophies",
        botStatus                       = "BotStatus",
        settings                        = "Settings",
        advancedSettings                = "AdvancedSettings",
        vendorSettings                  = "VendorSettings",
        salvageSettings                 = "SalvageSettings",
        gatherSettings                  = "GatherSettings",
        dragonHoloFarming				= "FarmDragonHolograms",
		
        -- meshmanager.lua
        meshManager                     = "MeshManager",
        queensdale                      = "Queensdale",
        harathiHinterlands              = "HarathiHinterlands",
        divinitysReach                  = "DivinitysReach",
        plainsOfAshford                 = "PlainsofAshford",
        blazeridgeSteppes               = "BlazeridgeSteppes",
        fieldsOfRuin                    = "FieldsofRuin",
        fireheartRise                   = "FireheartRise",
        kessexHills                     = "KessexHills",
        gendarranFields                 = "GendarranFields",
        ironMarches                     = "IronMarches",
        dredgehauntCliffs               = "DredgehauntCliffs",
        lornarsPass                     = "LornarsPass",
        wayfarerFoothills               = "WayfarerFoothills",
        timberlineFalls                 = "TimberlineFalls",
        frostgorgeSound                 = "FrostgorgeSound",
        snowdenDrifts                   = "SnowdenDrifts",
        diessaPlateau                   = "DiessaPlateau",
        ascalonianCatacombsStory        = "AscalonianCatacombs(Story)",
        caledonForest                   = "CaledonForest",
        metricaProvince                 = "MetricaProvince",
        ascalonianCatacombsExp          = "AscalonianCatacombs(Explo)",
        eternalBattlegrounds            = "EternalBattlegrounds",
        mountMaelstrom                  = "MountMaelstrom",
        lionsArch                       = "LionsArch",
        straightsOfDevastation          = "StraitsOfDevastation",
        sparkflyFen                     = "SparkflyFen",
        brisbanWildlands                = "BrisbanWildlands",
        cursedShore                     = "CursedShore",
        malchorsLeap                    = "MalchorsLeap",
        citadelOfFlamesStory            = "CitadelOfFlames(Story)",
        citadelOfFlamesExp              = "CitadelOfFlames(Explo)",
        bloodtideCoast                  = "BloodtideCoast",
        theGrove                        = "TheGrove",
        borderlands1                    = "BlueGreenRedBorderlands1",
        borderlands2                    = "BlueGreenRedBorderlands2",
        borderlands3                    = "BlueGreenRedBorderlands3",
        rataSum                         = "RataSum",
        blackCitadel                    = "BlackCitadel",
        hoelbrak                        = "Hoelbrak",
        southsunCove                    = "SouthsunCove",
        activated                       = "Activated",
        mapName                         = "Map",
        navmesh                         = "Navmesh",
        waypoint                        = "Waypoint",
        generalSettings                 = "GeneralSettings",
        dungeonManager                  = "DungeonManager",
        status                          = "Status",
        setPartySize                    = "Set PartySize",
        dungeons                        = "Dungeons",
        leaveDungeon                    = "Leave Dungeon",
        resetDungeon                    = "Reset Dungeon",
        stopDungeonManager              = "Stop DungeonManager",

        -- partymanager.lua
        partyManager                    = "PartyManager",
        enterCharNames                  = "Enter Character Names:",
        member1                         = "Member1",
        member2                         = "Member2",
        member3                         = "Member3",
        member4                         = "Member4",
        member5                         = "Member5",
        groupInfo                       = "GroupInfo",

        -- skillmanager.lua
        skillManager                    = "SkillManager",
        profile                         = "Profile",  
		sMmode							= "Mode",
		refreshProfiles                 = "Refresh Profile List",
		saveProfile                 	= "Save Current Profile",
        deleteProfile                   = "Delete Current Profile",
        newProfileName                  = "New Profile Name",
        newProfile                      = "New Profile",
        autoetectSkills                 = "Autodetect Skills",
        skillEditor                     = "Skill Editor",
        enabled                         = "Enabled",
        priority                        = "Priority",
        cooldown                        = "Cooldown",
        minRange                        = "MinRange",
        maxRange                        = "MaxRange",
        isGroundTargeted                = "IsGroundTargeted",
        targetType                      = "TargetType",
        useInCombat                     = "UseInCombat",
        playerMoving                    = "Player Moving",
        playerHPGT                      = "Player HP% >",
        playerHPLT                      = "Player HP% <",
        playerPowerGT                   = "Player Power% >",
        playerPowerLT                   = "Player Power% <",
        playerHas                       = "Player has ",
        orPlayerHas                     = "or Player has ",
        playerHasNot                    = "Player has NOT ",
        orPlayerHasNot                  = "or Player has NOT ",
        targetMoving                    = "Target Moving",
        targetHPGT                      = "Target HP% >",
        targetHPLT                      = "Target HP% <",
        targetDistanceGT                = "Target Distance >",
        targetDistanceLT                = "Target Distance <",
        enemiesNearCount                = "Enemies Near Target(Count) >=",
        enemiesNearRange                = "Enemies Near Target(MaxRange) =",
        alliesNearCount                 = "Allies Near Target(Count) >=",
        alliesNearRange                 = "Allies Near Target(MaxRange) =",
        targetHas                       = "Target has ",
        orTargetHas                     = "or Target has ",
        targetHasNot                    = "Target has NOT ",
        orTargetHasNot                  = "or Target has NOT ",

        -- leader.lua
        browserStats                    = "Enable BrowserStats",
        groupBotting                    = "Enable Groupbotting",
        serverIP                        = "MultiBotComServer IP",
        serverPort                      = "MultiBotComServer Port",
        serverPW                        = "MultiBotComServer Password",
        groupBotting                    = "GroupBotting",

        --salvaging.lua
        rarityJunk                      = "Junk",
        rarityCommon                    = "Common",
        rarityFine                      = "Fine",
        rarityMasterwork                = "Masterwork",
        rarityRare                      = "Rare",
        rarityExotic                    = "Exotic",
        salvage                         = "Salvage ",
        enableSalvage                   = "EnableSalvage",
    }
}
    