gCurrentLanguage = "us"

strings =
{
    ["us"] =
    {
        -- gw2.lua
        startStop                       = "StartStop",
        doPulse                         = "Pulse(Debug)",
        pulseTime                       = "Pulse Time (ms)",
        enableLog                       = "Enable Log",
        task                            = "Task",
        state                           = "State",
        effect                          = "Effect",
        autoStartBot                    = "AutoStartBot",
        combatMovement                  = "EnableCombatMovement",
        enableEvents                    = "EnableEvents",
        enableRepair                    = "EnableRepair",
        ignoreLevelMarker               = "IgnoreLevelMarker",
        wpVendor                        = "UseWPForVendor",
        wpEvents                        = "UseWPForEvents",
        enableUnstuck                   = "EnableUnstuck",
        unstuckCount                    = "UnstuckExitCount",
        eventTimeout                    = "EventTimeout",
        blacklistEvent                  = "BlacklistEvent",
        prioEvent                       = "Events>Aggro",
        prioRevive                      = "Revive>Aggro",
        vendorRarity                    = "MaxItemSellRarity",
        sellWeapon                      = "SellWeapons",
        sellArmor                       = "SellArmor",
        sellTrinket                     = "SellTrinkets",
        sellUpgrade                     = "SellUpgradeComponents",
        sellCrafting                    = "SellCraftingMats",
        sellTrophy                      = "SellTrophies",
        enableGather                    = "EnableGathering",
        buyTools                        = "BuyGatheringTools",
        buyBestTool                     = "BuyBestTool",
        toolRarity                      = "ToolRarity",
        toolStock                       = "ToolStock",
        enableSalvage                   = "EnableSalvaging",
        buyKits                         = "BuySalvageKits",
        buyBestKit                      = "BuyBestKit",
        kitRarity                       = "KitRarity",
        kitStock                        = "KitStock",
        salvageTrophy                   = "SalvageTrophies",
        botStatus                       = "BotStatus",
        settings                        = "Settings",
        advancedSettings                = "AdvancedSettings",
        vendorSettings                  = "VendorSettings",
        salvageSettings                 = "SalvageSettings",
        gatherSettings                  = "GatherSettings",
        skipcutscene					= "Skip Cutscenes",
		depositItems					= "Deposit Items",
		checkChat						= "Chat Alert",
		
		
        -- meshmanager.lua
        meshManager                     = "MeshManager",
        queensdale                      = "Queensdale",
        harathiHinterlands              = "HarathiHinterlands",
        divinitysReach                  = "DivinitysReach",
        plainsOfAshford                 = "PlainsofAshford",
        blazeridgeSteppes               = "BlazeridgeSteppes",
        fieldsOfRuin                    = "FieldsofRuin",
        fireheartRise                   = "FireheartRise",
        kessexHills                     = "KessexHills",
        gendarranFields                 = "GendarranFields",
        ironMarches                     = "IronMarches",
        dredgehauntCliffs               = "DredgehauntCliffs",
        lornarsPass                     = "LornarsPass",
        wayfarerFoothills               = "WayfarerFoothills",
        timberlineFalls                 = "TimberlineFalls",
        frostgorgeSound                 = "FrostgorgeSound",
        snowdenDrifts                   = "SnowdenDrifts",
        diessaPlateau                   = "DiessaPlateau",
        ascalonianCatacombsStory        = "AscalonianCatacombs(Story)",
        caledonForest                   = "CaledonForest",
        metricaProvince                 = "MetricaProvince",
        ascalonianCatacombsExp          = "AscalonianCatacombs(Explo)",
        eternalBattlegrounds            = "EternalBattlegrounds",
        mountMaelstrom                  = "MountMaelstrom",
        lionsArch                       = "LionsArch",
        straightsOfDevastation          = "StraitsOfDevastation",
        sparkflyFen                     = "SparkflyFen",
        brisbanWildlands                = "BrisbanWildlands",
        cursedShore                     = "CursedShore",
        malchorsLeap                    = "MalchorsLeap",
        citadelOfFlamesStory            = "CitadelOfFlames(Story)",
        citadelOfFlamesExp              = "CitadelOfFlames(Explo)",
        bloodtideCoast                  = "BloodtideCoast",
        theGrove                        = "TheGrove",
        borderlands1                    = "BlueGreenRedBorderlands1",
        borderlands2                    = "BlueGreenRedBorderlands2",
        borderlands3                    = "BlueGreenRedBorderlands3",
        rataSum                         = "RataSum",
        blackCitadel                    = "BlackCitadel",
        hoelbrak                        = "Hoelbrak",
        southsunCove                    = "SouthsunCove",
        activated                       = "Activated",
        mapName                         = "Map",
        navmesh                         = "Navmesh",
        waypoint                        = "Waypoint",
        generalSettings                 = "GeneralSettings",
		getWaypoint						= "GetMeshWP",
		useInSwitcher					= "UseInSwitcher",
		enableSwitcher					= "EnableSwitcher",
		minSwitchTime			        = "MinSwitchTime",
		maxSwitchTime					= "MaxSwitchTime",
		switchTimer						= "TimeUntilSwitch",
		switcherSettings				= "SwitcherSettings",
		showMesh						= "Show Mesh",
		newMeshName						= "New Meshfile Name",
		newMesh							= "Create New Meshfile",
		saveMesh						= "Save Mesh to File",
		buildNAVMesh					= "Build NAVMesh",
		editor							= "Editor",
        enablePSwitch					= "EnableParanoiaSwitch",
        pSwitchCount                    = "ParanoiaPlayerCount",

		-- dungeonmanager.lua
        dungeonManager                  = "DungeonManager",
        status                          = "Status",
        setPartySize                    = "Set PartySize",
        dungeons                        = "Dungeons",
        leaveDungeon                    = "Leave Dungeon",
        resetDungeon                    = "Reset Dungeon",
        stopDungeonManager              = "Stop DungeonManager",

        -- partymanager.lua
        partyManager                    = "PartyManager",
        enterCharNames                  = "Enter Character Names:",
        member1                         = "Member1",
        member2                         = "Member2",
        member3                         = "Member3",
        member4                         = "Member4",
        member5                         = "Member5",
        groupInfo                       = "GroupInfo",

        -- skillmanager.lua
        skillManager                    = "SkillManager",
        profile                         = "Profile",
		sMmode							= "Attack Mode",
		sMtargetmode					= "Target Mode",
		refreshProfiles                 = "Refresh Profile List",
		saveProfile                 	= "Save Current Profile",
        deleteProfile                   = "Delete Current Profile",
        newProfileName                  = "New Profile Name",
        newProfile                      = "New Profile",
        autoetectSkills                 = "Autodetect Skills",
		refreshSkillList                 = "Clear & Refresh SkillList",
        skillEditor                     = "Skill Editor",
        enabled                         = "Enabled",
        priority                        = "Priority",
        los                  		    = "Needs LineOfSight",
		cooldown                        = "Cooldown",
        minRange                        = "MinRange",
        maxRange                        = "MaxRange",
        isGroundTargeted                = "Is GroundTargeted",
        targetType                      = "TargetType",
        useOutOfCombat                  = "Use out of Combat",
        playerMoving                    = "Player Moving",
        playerHPGT                      = "Player HP% >",
        playerHPLT                      = "Player HP% <",
        playerPowerGT                   = "Player Power% >",
        playerPowerLT                   = "Player Power% <",
        playerHas                       = "Player has ",
        orPlayerHas                     = "or Player has ",
        playerHasNot                    = "Player has NOT ",
		orPlayerCond					= "Player has #Conditions >",
        orPlayerHasNot                  = "or Player has NOT ",
        targetMoving                    = "Target Moving",
        targetHPGT                      = "Target HP% >",
        targetHPLT                      = "Target HP% <",
        targetDistanceGT                = "Target Distance >",
        targetDistanceLT                = "Target Distance <",
        enemiesNearCount                = "Enemies Near Target(Count) >=",
        enemiesNearRange                = "Enemies Near Target(MaxRange) =",
        alliesNearCount                 = "Allies Near Target(Count) >=",
        alliesNearRange                 = "Allies Near Target(MaxRange) =",
        targetHas                       = "Target has ",
        orTargetHas                     = "or Target has ",
        targetHasNot                    = "Target has NOT ",
        orTargetHasNot                  = "or Target has NOT ",
		AdvancedSettings				= "Advanced Settings",
		SwapA							= "Swap Weapons",
		SwapR							= "Swap Randomly",
		SwapCD							= "Swap when Skill 2-5 on CD",
		SwapRange						= "Swap when Target out of Range",
		PriorizeKit						= "Prioritize Kit",
		PriorizeAttunement				= "Prioritize Attunement",
		AutoStomp						= "Finish Enemy",
		AutoRezz						= "Rezz Friendly",
		Fightstyle						= "Fightstyle",
		
        -- leader.lua
        browserStats                    = "Enable BrowserStats",
        groupBotting                    = "Enable Groupbotting",
        serverIP                        = "MultiBotComServer IP",
        serverPort                      = "MultiBotComServer Port",
        serverPW                        = "MultiBotComServer Password",
        groupBotting                    = "GroupBotting",

        -- salvaging.lua
        rarityJunk                      = "Junk",
        rarityCommon                    = "Common",
        rarityFine                      = "Fine",
        rarityMasterwork                = "Masterwork",
        rarityRare                      = "Rare",
        rarityExotic                    = "Exotic",
        salvage                         = "Salvage ",
        enableSalvage                   = "EnableSalvage",

        -- common profession
        allowedRange                    = "Allowed Range [0-100], 0=Disabled",
        skill7HP                        = "Use Skill7 at HP%",
        skill8HP                        = "Use Skill8 at HP%",
        skill9HP                        = "Use Skill9 at HP%",
        eliteHP                         = "Use Elite  at HP%",
        autoF1                          = "AutoUse F1",
        autoF2                          = "AutoUse F2",
        autoF3                          = "AutoUse F3",

        -- elementalist.lua
        autoSwapAttunements             = "AutoSwapAttunements",
        elementalistSettings            = "Elementalist-Settings",

        -- engineer.lua
        autoSwapToKits                  = "AutoSwapToKits",
        engineerSettings                = "Engineer-Settings",

        -- guardian.lua
        autoSwapWeaponSets              = "AutoSwapWeaponSets",
        guardianSettings                = "Guardian-Settings",

        -- mesmer.lua
        mesmerSettings                  = "Mesmer-Settings",

        -- necromancer.lua
        autoUsePets                     = "AutoUsePets",
        necromancerSettings             = "Necromancer-Settings",

        -- ranger.lua
        rangerSettings                  = "Ranger-Settings",

        -- thief.lua
        thiefSettings                   = "Thief-Settings",

        -- warrior.lua
        warriorSettings                 = "Warrior-Settings",

        -- meshassistant.lua
        maModuleName                    = "MeshAssistant",
        maMarkerInspector               = "MarkerInspector",
        maMarkerTypeNone                = "None",
        maMarkerTypeFarmSpot            = "FarmSpot",
        maMarkerTypeWaypoint            = "Waypoint",
        maMarkerTypePointOfInterest     = "PointOfInterest",
        maMarkerTypeVista               = "Vista",
        maMarkerTypeSkillPoint          = "SkillPoint",
        maMarkerTypeHeartQuest          = "HeartQuest",
        maMarkerTypeRepairVendor        = "RepairVendor",
        maStartStopAutoMeshing          = "Start / Stop Auto Meshing",
        maEditMesh                      = "Edit Mesh Mode",
        maLoadExistingMesh              = "Load Existing Mesh",
        maNewResetMesh                  = "New / Reset Mesh",
        maShowHideMesh                  = "Show / Hide Mesh",
        maVersion                       = "Version",
        maTrianglesTotal                = "# Triangles Total",
        maVerticesTotal                 = "# Vertices Total",
        maVerticesCreatedThisSession    = "# Vertices Created This Session",
        maQueueSize                     = "Queue Size",
        maOpenMarkerInspector           = "Open Marker Inspector",
        maUndoCells1                    = "Undo 100 Cells (+stop)",
        maUndoCells2                    = "Undo 500 Cells (+stop)",
        maUndoCells3                    = "Undo 1000 Cells (+stop)",
        maToggleSteepSettings           = "Toggle Steep Settings",
        maToggleWideSettings            = "Toggle Wide Settings",
        maHideUnselectedVertices        = "Hide Unselected Vertices",
        maUseQueue                      = "Use Queue",
        maUpdateInterval                = "Update Interval",
        maNormalDistance                = "Normal Distance",
        maForceWideAreaDistance         = "Force Wide Area Distance",
        maForceRadiusNormal             = "Force Radius Normal",
        maForceRadiusWide               = "Force Radius Wide",
        maForceCellDistance             = "Force Cell Distance",
        maQueueElementsPerTick          = "Queue Elements Per Tick",
        maQueueElementsPerTickInc       = "Queue Elements Per Tick Increments",
        maAngleThreshold                = "Angle Threshold",
        maCellWidth                     = "Cell Width",
        maSingleZThresholdNormal        = "Single Height Threshold Normal",
        maSingleZThresholdSteep         = "Single Height Threshold Steep",
        maHeightThresholdHigh           = "High Hight Threshold",
        maHeightThresholdLow            = "Low Hight Threshold",
        maPointGridDistance             = "Cloud Point Distance",
        maGroupInfo                     = "Info",
        maGroupToolbox                  = "Toolbox",
        maGroupInputSettings            = "Input Settings",
        maGroupDisplaySettings          = "Display Settings",
        maGroupBasicSettings            = "Basic Settings",
        maGroupAdvancedSettings         = "Advanced Settings",
        maGroupExpertSettings           = "Expert Settings",
        maMarkerID                      = "ID",
        maMarkerName                    = "Name",
        maMarkerType                    = "Type",
        maMarkerMinLevel                = "Minimum Level",
        maMarkerMaxLevel                = "Maximum Level",
        maMarkerDeleteMarker            = "Delete Marker",
        maMarkerSelectToEdit            = "Select To Edit",
        maMarkerNewName                 = "NewMarker",
        maMarkerGroupDetails            = "Details",
        maMarkerGroupAllMarkers         = "All Markers",
        maDontTouchLoadedMesh           = "Don't Touch Loaded Mesh",
        maEdgeHitCheckPoints            = "Edge Hit Check Points",
        maMeshWaterSurfaces             = "Mesh Water Surface",
        maDisableShowDebugMessages      = "Disable Debug Console Messages"
    },
    ["de"] =
        {
        -- gw2.lua
        startStop                       = "StartStop",
        doPulse                         = "Pulse(Debug)",
        pulseTime                       = "Pulse Time (ms)",
        enableLog                       = "Enable Log",
        task                            = "Task",
        state                           = "State",
        effect                          = "Effect",
        autoStartBot                    = "AutoStartBot",
        combatMovement                  = "EnableCombatMovement",
        enableEvents                    = "EnableEvents",
        enableRepair                    = "EnableRepair",
        ignoreLevelMarker               = "IgnoreLevelMarker",
        wpVendor                        = "UseWPForVendor",
        wpEvents                        = "UseWPForEvents",
        enableUnstuck                   = "EnableUnstuck",
        unstuckCount                    = "UnstuckExitCount",
        eventTimeout                    = "EventTimeout",
        blacklistEvent                  = "BlacklistEvent",
        prioEvent                       = "Events>Aggro",
        prioRevive                      = "Revive>Aggro",
        vendorRarity                    = "MaxItemSellRarity",
        sellWeapon                      = "SellWeapons",
        sellArmor                       = "SellArmor",
        sellTrinket                     = "SellTrinkets",
        sellUpgrade                     = "SellUpgradeComponents",
        sellCrafting                    = "SellCraftingMats",
        sellTrophy                      = "SellTrophies",
        enableGather                    = "EnableGathering",
        buyTools                        = "BuyGatheringTools",
        buyBestTool                     = "BuyBestTool",
        toolRarity                      = "ToolRarity",
        toolStock                       = "ToolStock",
        enableSalvage                   = "EnableSalvaging",
        buyKits                         = "BuySalvageKits",
        buyBestKit                      = "BuyBestKit",
        kitRarity                       = "KitRarity",
        kitStock                        = "KitStock",
        salvageTrophy                   = "SalvageTrophies",
        botStatus                       = "BotStatus",
        settings                        = "Settings",
        advancedSettings                = "AdvancedSettings",
        vendorSettings                  = "VendorSettings",
        salvageSettings                 = "SalvageSettings",
        gatherSettings                  = "GatherSettings",
        skipcutscene					= "Skip Cutscenes",

        -- meshmanager.lua
        meshManager                     = "MeshManager",
        queensdale                      = "Queensdale",
        harathiHinterlands              = "HarathiHinterlands",
        divinitysReach                  = "DivinitysReach",
        plainsOfAshford                 = "PlainsofAshford",
        blazeridgeSteppes               = "BlazeridgeSteppes",
        fieldsOfRuin                    = "FieldsofRuin",
        fireheartRise                   = "FireheartRise",
        kessexHills                     = "KessexHills",
        gendarranFields                 = "GendarranFields",
        ironMarches                     = "IronMarches",
        dredgehauntCliffs               = "DredgehauntCliffs",
        lornarsPass                     = "LornarsPass",
        wayfarerFoothills               = "WayfarerFoothills",
        timberlineFalls                 = "TimberlineFalls",
        frostgorgeSound                 = "FrostgorgeSound",
        snowdenDrifts                   = "SnowdenDrifts",
        diessaPlateau                   = "DiessaPlateau",
        ascalonianCatacombsStory        = "AscalonianCatacombs(Story)",
        caledonForest                   = "CaledonForest",
        metricaProvince                 = "MetricaProvince",
        ascalonianCatacombsExp          = "AscalonianCatacombs(Explo)",
        eternalBattlegrounds            = "EternalBattlegrounds",
        mountMaelstrom                  = "MountMaelstrom",
        lionsArch                       = "LionsArch",
        straightsOfDevastation          = "StraitsOfDevastation",
        sparkflyFen                     = "SparkflyFen",
        brisbanWildlands                = "BrisbanWildlands",
        cursedShore                     = "CursedShore",
        malchorsLeap                    = "MalchorsLeap",
        citadelOfFlamesStory            = "CitadelOfFlames(Story)",
        citadelOfFlamesExp              = "CitadelOfFlames(Explo)",
        bloodtideCoast                  = "BloodtideCoast",
        theGrove                        = "TheGrove",
        borderlands1                    = "BlueGreenRedBorderlands1",
        borderlands2                    = "BlueGreenRedBorderlands2",
        borderlands3                    = "BlueGreenRedBorderlands3",
        rataSum                         = "RataSum",
        blackCitadel                    = "BlackCitadel",
        hoelbrak                        = "Hoelbrak",
        southsunCove                    = "SouthsunCove",
        activated                       = "Activated",
        mapName                         = "Map",
        navmesh                         = "Navmesh",
        waypoint                        = "Waypoint",
        generalSettings                 = "GeneralSettings",
        dungeonManager                  = "DungeonManager",
        status                          = "Status",
        setPartySize                    = "Set PartySize",
        dungeons                        = "Dungeons",
        leaveDungeon                    = "Leave Dungeon",
        resetDungeon                    = "Reset Dungeon",
        stopDungeonManager              = "Stop DungeonManager",

        -- partymanager.lua
        partyManager                    = "PartyManager",
        enterCharNames                  = "Enter Character Names:",
        member1                         = "Member1",
        member2                         = "Member2",
        member3                         = "Member3",
        member4                         = "Member4",
        member5                         = "Member5",
        groupInfo                       = "GroupInfo",

        -- skillmanager.lua
        skillManager                    = "SkillManager",
        profile                         = "Profile",
		refreshProfiles                 = "Refresh Profile List",
		saveProfile                 	= "Save Current Profile",
        deleteProfile                   = "Delete Current Profile",
        newProfileName                  = "New Profile Name",
        newProfile                      = "New Profile",
        autoetectSkills                 = "Autodetect Skills",
        skillEditor                     = "Skill Editor",
        enabled                         = "Enabled",
        priority                        = "Priority",
        cooldown                        = "Cooldown",
        minRange                        = "MinRange",
        maxRange                        = "MaxRange",
        isGroundTargeted                = "IsGroundTargeted",
        targetType                      = "TargetType",
        useInCombat                     = "UseInCombat",
        playerMoving                    = "Player Moving",
        playerHPGT                      = "Player HP% >",
        playerHPLT                      = "Player HP% <",
        playerPowerGT                   = "Player Power% >",
        playerPowerLT                   = "Player Power% <",
        playerHas                       = "Player has ",
        orPlayerHas                     = "or Player has ",
        playerHasNot                    = "Player has NOT ",
        orPlayerHasNot                  = "or Player has NOT ",
        targetMoving                    = "Target Moving",
        targetHPGT                      = "Target HP% >",
        targetHPLT                      = "Target HP% <",
        targetDistanceGT                = "Target Distance >",
        targetDistanceLT                = "Target Distance <",
        enemiesNearCount                = "Enemies Near Target(Count) >=",
        enemiesNearRange                = "Enemies Near Target(MaxRange) =",
        alliesNearCount                 = "Allies Near Target(Count) >=",
        alliesNearRange                 = "Allies Near Target(MaxRange) =",
        targetHas                       = "Target has ",
        orTargetHas                     = "or Target has ",
        targetHasNot                    = "Target has NOT ",
        orTargetHasNot                  = "or Target has NOT ",

        -- leader.lua
        browserStats                    = "Enable BrowserStats",
        groupBotting                    = "Enable Groupbotting",
        serverIP                        = "MultiBotComServer IP",
        serverPort                      = "MultiBotComServer Port",
        serverPW                        = "MultiBotComServer Password",
        groupBotting                    = "GroupBotting",

        -- salvaging.lua
        rarityJunk                      = "Junk",
        rarityCommon                    = "Common",
        rarityFine                      = "Fine",
        rarityMasterwork                = "Masterwork",
        rarityRare                      = "Rare",
        rarityExotic                    = "Exotic",
        salvage                         = "Salvage ",
        enableSalvage                   = "EnableSalvage",

        -- common profession
        allowedRange                    = "Allowed Range [0-100], 0=Disabled",
        skill7HP                        = "Use Skill7 at HP%",
        skill8HP                        = "Use Skill8 at HP%",
        skill9HP                        = "Use Skill9 at HP%",
        eliteHP                         = "Use Elite  at HP%",
        autoF1                          = "AutoUse F1",
        autoF2                          = "AutoUse F2",
        autoF3                          = "AutoUse F3",

        -- elementalist.lua
        autoSwapAttunements             = "AutoSwapAttunements",
        elementalistSettings            = "Elementalist-Settings",

        -- engineer.lua
        autoSwapToKits                  = "AutoSwapToKits",
        engineerSettings                = "Engineer-Settings",

        -- guardian.lua
        autoSwapWeaponSets              = "AutoSwapWeaponSets",
        guardianSettings                = "Guardian-Settings",

        -- mesmer.lua
        mesmerSettings                  = "Mesmer-Settings",

        -- necromancer.lua
        autoUsePets                     = "AutoUsePets",
        necromancerSettings             = "Necromancer-Settings",

        -- ranger.lua
        rangerSettings                  = "Ranger-Settings",

        -- thief.lua
        thiefSettings                   = "Thief-Settings",

        -- warrior.lua
        warriorSettings                 = "Warrior-Settings",

        -- meshassistant.lua
        maModuleName                    = "MeshAssistant",
        maMarkerInspector               = "MarkerInspector",
        maMarkerTypeNone                = "None",
        maMarkerTypeFarmSpot            = "FarmSpot",
        maMarkerTypeWaypoint            = "Waypoint",
        maMarkerTypePointOfInterest     = "PointOfInterest",
        maMarkerTypeVista               = "Vista",
        maMarkerTypeSkillPoint          = "SkillPoint",
        maMarkerTypeHeartQuest          = "HeartQuest",
        maMarkerTypeRepairVendor        = "RepairVendor",
        maStartStopAutoMeshing          = "Start / Stop Auto Meshing",
        maEditMesh                      = "Edit Mesh Mode",
        maLoadExistingMesh              = "Load Existing Mesh",
        maNewResetMesh                  = "New / Reset Mesh",
        maShowHideMesh                  = "Show / Hide Mesh",
        maVersion                       = "Version",
        maTrianglesTotal                = "# Triangles Total",
        maVerticesTotal                 = "# Vertices Total",
        maVerticesCreatedThisSession    = "# Vertices Created This Session",
        maQueueSize                     = "Queue Size",
        maOpenMarkerInspector           = "Open Marker Inspector",
        maUndoCells1                    = "Undo 100 Cells (+stop)",
        maUndoCells2                    = "Undo 500 Cells (+stop)",
        maUndoCells3                    = "Undo 1000 Cells (+stop)",
        maToggleSteepSettings           = "Toggle Steep Settings",
        maToggleWideSettings            = "Toggle Wide Settings",
        maHideUnselectedVertices        = "Hide Unselected Vertices",
        maUseQueue                      = "Use Queue",
        maUpdateInterval                = "Update Interval",
        maNormalDistance                = "Normal Distance",
        maForceWideAreaDistance         = "Force Wide Area Distance",
        maForceRadiusNormal             = "Force Radius Normal",
        maForceRadiusWide               = "Force Radius Wide",
        maForceCellDistance             = "Force Cell Distance",
        maQueueElementsPerTick          = "Queue Elements Per Tick",
        maQueueElementsPerTickInc       = "Queue Elements Per Tick Increments",
        maAngleThreshold                = "Angle Threshold",
        maCellWidth                     = "Cell Width",
        maSingleZThresholdNormal        = "Single Height Threshold Normal",
        maSingleZThresholdSteep         = "Single Height Threshold Steep",
        maHeightThresholdHigh           = "High Hight Threshold",
        maHeightThresholdLow            = "Low Hight Threshold",
        maPointGridDistance             = "Cloud Point Distance",
        maGroupInfo                     = "Info",
        maGroupToolbox                  = "Toolbox",
        maGroupInputSettings            = "Input Settings",
        maGroupDisplaySettings          = "Display Settings",
        maGroupBasicSettings            = "Basic Settings",
        maGroupAdvancedSettings         = "Advanced Settings",
        maGroupExpertSettings           = "Expert Settings",
        maMarkerID                      = "ID",
        maMarkerName                    = "Name",
        maMarkerType                    = "Type",
        maMarkerMinLevel                = "Minimum Level",
        maMarkerMaxLevel                = "Maximum Level",
        maMarkerDeleteMarker            = "Delete Marker",
        maMarkerSelectToEdit            = "Select To Edit",
        maMarkerNewName                 = "NewMarker",
        maMarkerGroupDetails            = "Details",
        maMarkerGroupAllMarkers         = "All Markers",
        maDontTouchLoadedMesh           = "Don't Touch Loaded Mesh",
        maEdgeHitCheckPoints            = "Edge Hit Check Points",
        maMeshWaterSurfaces             = "Mesh Water Surface",
        maDisableShowDebugMessages      = "Disable Debug Console Messages"
    },
    ["fr"] =
       {
        -- gw2.lua
        startStop                       = "StartStop",
        doPulse                         = "Pulse(Debug)",
        pulseTime                       = "Pulse Time (ms)",
        enableLog                       = "Enable Log",
        task                            = "Task",
        state                           = "State",
        effect                          = "Effect",
        autoStartBot                    = "AutoStartBot",
        combatMovement                  = "EnableCombatMovement",
        enableEvents                    = "EnableEvents",
        enableRepair                    = "EnableRepair",
        ignoreLevelMarker               = "IgnoreLevelMarker",
        wpVendor                        = "UseWPForVendor",
        wpEvents                        = "UseWPForEvents",
        enableUnstuck                   = "EnableUnstuck",
        unstuckCount                    = "UnstuckExitCount",
        eventTimeout                    = "EventTimeout",
        blacklistEvent                  = "BlacklistEvent",
        prioEvent                       = "Events>Aggro",
        prioRevive                      = "Revive>Aggro",
        vendorRarity                    = "MaxItemSellRarity",
        sellWeapon                      = "SellWeapons",
        sellArmor                       = "SellArmor",
        sellTrinket                     = "SellTrinkets",
        sellUpgrade                     = "SellUpgradeComponents",
        sellCrafting                    = "SellCraftingMats",
        sellTrophy                      = "SellTrophies",
        enableGather                    = "EnableGathering",
        buyTools                        = "BuyGatheringTools",
        buyBestTool                     = "BuyBestTool",
        toolRarity                      = "ToolRarity",
        toolStock                       = "ToolStock",
        enableSalvage                   = "EnableSalvaging",
        buyKits                         = "BuySalvageKits",
        buyBestKit                      = "BuyBestKit",
        kitRarity                       = "KitRarity",
        kitStock                        = "KitStock",
        salvageTrophy                   = "SalvageTrophies",
        botStatus                       = "BotStatus",
        settings                        = "Settings",
        advancedSettings                = "AdvancedSettings",
        vendorSettings                  = "VendorSettings",
        salvageSettings                 = "SalvageSettings",
        gatherSettings                  = "GatherSettings",
        skipcutscene					= "Skip Cutscenes",

        -- meshmanager.lua
        meshManager                     = "MeshManager",
        queensdale                      = "Queensdale",
        harathiHinterlands              = "HarathiHinterlands",
        divinitysReach                  = "DivinitysReach",
        plainsOfAshford                 = "PlainsofAshford",
        blazeridgeSteppes               = "BlazeridgeSteppes",
        fieldsOfRuin                    = "FieldsofRuin",
        fireheartRise                   = "FireheartRise",
        kessexHills                     = "KessexHills",
        gendarranFields                 = "GendarranFields",
        ironMarches                     = "IronMarches",
        dredgehauntCliffs               = "DredgehauntCliffs",
        lornarsPass                     = "LornarsPass",
        wayfarerFoothills               = "WayfarerFoothills",
        timberlineFalls                 = "TimberlineFalls",
        frostgorgeSound                 = "FrostgorgeSound",
        snowdenDrifts                   = "SnowdenDrifts",
        diessaPlateau                   = "DiessaPlateau",
        ascalonianCatacombsStory        = "AscalonianCatacombs(Story)",
        caledonForest                   = "CaledonForest",
        metricaProvince                 = "MetricaProvince",
        ascalonianCatacombsExp          = "AscalonianCatacombs(Explo)",
        eternalBattlegrounds            = "EternalBattlegrounds",
        mountMaelstrom                  = "MountMaelstrom",
        lionsArch                       = "LionsArch",
        straightsOfDevastation          = "StraitsOfDevastation",
        sparkflyFen                     = "SparkflyFen",
        brisbanWildlands                = "BrisbanWildlands",
        cursedShore                     = "CursedShore",
        malchorsLeap                    = "MalchorsLeap",
        citadelOfFlamesStory            = "CitadelOfFlames(Story)",
        citadelOfFlamesExp              = "CitadelOfFlames(Explo)",
        bloodtideCoast                  = "BloodtideCoast",
        theGrove                        = "TheGrove",
        borderlands1                    = "BlueGreenRedBorderlands1",
        borderlands2                    = "BlueGreenRedBorderlands2",
        borderlands3                    = "BlueGreenRedBorderlands3",
        rataSum                         = "RataSum",
        blackCitadel                    = "BlackCitadel",
        hoelbrak                        = "Hoelbrak",
        southsunCove                    = "SouthsunCove",
        activated                       = "Activated",
        mapName                         = "Map",
        navmesh                         = "Navmesh",
        waypoint                        = "Waypoint",
        generalSettings                 = "GeneralSettings",
        dungeonManager                  = "DungeonManager",
        status                          = "Status",
        setPartySize                    = "Set PartySize",
        dungeons                        = "Dungeons",
        leaveDungeon                    = "Leave Dungeon",
        resetDungeon                    = "Reset Dungeon",
        stopDungeonManager              = "Stop DungeonManager",

        -- partymanager.lua
        partyManager                    = "PartyManager",
        enterCharNames                  = "Enter Character Names:",
        member1                         = "Member1",
        member2                         = "Member2",
        member3                         = "Member3",
        member4                         = "Member4",
        member5                         = "Member5",
        groupInfo                       = "GroupInfo",

        -- skillmanager.lua
        skillManager                    = "SkillManager",
        profile                         = "Profile",
		refreshProfiles                 = "Refresh Profile List",
		saveProfile                 	= "Save Current Profile",
        deleteProfile                   = "Delete Current Profile",
        newProfileName                  = "New Profile Name",
        newProfile                      = "New Profile",
        autoetectSkills                 = "Autodetect Skills",
        skillEditor                     = "Skill Editor",
        enabled                         = "Enabled",
        priority                        = "Priority",
        cooldown                        = "Cooldown",
        minRange                        = "MinRange",
        maxRange                        = "MaxRange",
        isGroundTargeted                = "IsGroundTargeted",
        targetType                      = "TargetType",
        useInCombat                     = "UseInCombat",
        playerMoving                    = "Player Moving",
        playerHPGT                      = "Player HP% >",
        playerHPLT                      = "Player HP% <",
        playerPowerGT                   = "Player Power% >",
        playerPowerLT                   = "Player Power% <",
        playerHas                       = "Player has ",
        orPlayerHas                     = "or Player has ",
        playerHasNot                    = "Player has NOT ",
        orPlayerHasNot                  = "or Player has NOT ",
        targetMoving                    = "Target Moving",
        targetHPGT                      = "Target HP% >",
        targetHPLT                      = "Target HP% <",
        targetDistanceGT                = "Target Distance >",
        targetDistanceLT                = "Target Distance <",
        enemiesNearCount                = "Enemies Near Target(Count) >=",
        enemiesNearRange                = "Enemies Near Target(MaxRange) =",
        alliesNearCount                 = "Allies Near Target(Count) >=",
        alliesNearRange                 = "Allies Near Target(MaxRange) =",
        targetHas                       = "Target has ",
        orTargetHas                     = "or Target has ",
        targetHasNot                    = "Target has NOT ",
        orTargetHasNot                  = "or Target has NOT ",

        -- leader.lua
        browserStats                    = "Enable BrowserStats",
        groupBotting                    = "Enable Groupbotting",
        serverIP                        = "MultiBotComServer IP",
        serverPort                      = "MultiBotComServer Port",
        serverPW                        = "MultiBotComServer Password",
        groupBotting                    = "GroupBotting",

        -- salvaging.lua
        rarityJunk                      = "Junk",
        rarityCommon                    = "Common",
        rarityFine                      = "Fine",
        rarityMasterwork                = "Masterwork",
        rarityRare                      = "Rare",
        rarityExotic                    = "Exotic",
        salvage                         = "Salvage ",
        enableSalvage                   = "EnableSalvage",

        -- common profession
        allowedRange                    = "Allowed Range [0-100], 0=Disabled",
        skill7HP                        = "Use Skill7 at HP%",
        skill8HP                        = "Use Skill8 at HP%",
        skill9HP                        = "Use Skill9 at HP%",
        eliteHP                         = "Use Elite  at HP%",
        autoF1                          = "AutoUse F1",
        autoF2                          = "AutoUse F2",
        autoF3                          = "AutoUse F3",

        -- elementalist.lua
        autoSwapAttunements             = "AutoSwapAttunements",
        elementalistSettings            = "Elementalist-Settings",

        -- engineer.lua
        autoSwapToKits                  = "AutoSwapToKits",
        engineerSettings                = "Engineer-Settings",

        -- guardian.lua
        autoSwapWeaponSets              = "AutoSwapWeaponSets",
        guardianSettings                = "Guardian-Settings",

        -- mesmer.lua
        mesmerSettings                  = "Mesmer-Settings",

        -- necromancer.lua
        autoUsePets                     = "AutoUsePets",
        necromancerSettings             = "Necromancer-Settings",

        -- ranger.lua
        rangerSettings                  = "Ranger-Settings",

        -- thief.lua
        thiefSettings                   = "Thief-Settings",

        -- warrior.lua
        warriorSettings                 = "Warrior-Settings",

        -- meshassistant.lua
        maModuleName                    = "MeshAssistant",
        maMarkerInspector               = "MarkerInspector",
        maMarkerTypeNone                = "None",
        maMarkerTypeFarmSpot            = "FarmSpot",
        maMarkerTypeWaypoint            = "Waypoint",
        maMarkerTypePointOfInterest     = "PointOfInterest",
        maMarkerTypeVista               = "Vista",
        maMarkerTypeSkillPoint          = "SkillPoint",
        maMarkerTypeHeartQuest          = "HeartQuest",
        maMarkerTypeRepairVendor        = "RepairVendor",
        maStartStopAutoMeshing          = "Start / Stop Auto Meshing",
        maEditMesh                      = "Edit Mesh Mode",
        maLoadExistingMesh              = "Load Existing Mesh",
        maNewResetMesh                  = "New / Reset Mesh",
        maShowHideMesh                  = "Show / Hide Mesh",
        maVersion                       = "Version",
        maTrianglesTotal                = "# Triangles Total",
        maVerticesTotal                 = "# Vertices Total",
        maVerticesCreatedThisSession    = "# Vertices Created This Session",
        maQueueSize                     = "Queue Size",
        maOpenMarkerInspector           = "Open Marker Inspector",
        maUndoCells1                    = "Undo 100 Cells (+stop)",
        maUndoCells2                    = "Undo 500 Cells (+stop)",
        maUndoCells3                    = "Undo 1000 Cells (+stop)",
        maToggleSteepSettings           = "Toggle Steep Settings",
        maToggleWideSettings            = "Toggle Wide Settings",
        maHideUnselectedVertices        = "Hide Unselected Vertices",
        maUseQueue                      = "Use Queue",
        maUpdateInterval                = "Update Interval",
        maNormalDistance                = "Normal Distance",
        maForceWideAreaDistance         = "Force Wide Area Distance",
        maForceRadiusNormal             = "Force Radius Normal",
        maForceRadiusWide               = "Force Radius Wide",
        maForceCellDistance             = "Force Cell Distance",
        maQueueElementsPerTick          = "Queue Elements Per Tick",
        maQueueElementsPerTickInc       = "Queue Elements Per Tick Increments",
        maAngleThreshold                = "Angle Threshold",
        maCellWidth                     = "Cell Width",
        maSingleZThresholdNormal        = "Single Height Threshold Normal",
        maSingleZThresholdSteep         = "Single Height Threshold Steep",
        maHeightThresholdHigh           = "High Hight Threshold",
        maHeightThresholdLow            = "Low Hight Threshold",
        maPointGridDistance             = "Cloud Point Distance",
        maGroupInfo                     = "Info",
        maGroupToolbox                  = "Toolbox",
        maGroupInputSettings            = "Input Settings",
        maGroupDisplaySettings          = "Display Settings",
        maGroupBasicSettings            = "Basic Settings",
        maGroupAdvancedSettings         = "Advanced Settings",
        maGroupExpertSettings           = "Expert Settings",
        maMarkerID                      = "ID",
        maMarkerName                    = "Name",
        maMarkerType                    = "Type",
        maMarkerMinLevel                = "Minimum Level",
        maMarkerMaxLevel                = "Maximum Level",
        maMarkerDeleteMarker            = "Delete Marker",
        maMarkerSelectToEdit            = "Select To Edit",
        maMarkerNewName                 = "NewMarker",
        maMarkerGroupDetails            = "Details",
        maMarkerGroupAllMarkers         = "All Markers",
        maDontTouchLoadedMesh           = "Don't Touch Loaded Mesh",
        maEdgeHitCheckPoints            = "Edge Hit Check Points",
        maMeshWaterSurfaces             = "Mesh Water Surface",
        maDisableShowDebugMessages      = "Disable Debug Console Messages"
    },
    ["ru"] =
        {
        -- gw2.lua
        startStop                       = "StartStop",
        doPulse                         = "Pulse(Debug)",
        pulseTime                       = "Pulse Time (ms)",
        enableLog                       = "Enable Log",
        task                            = "Task",
        state                           = "State",
        effect                          = "Effect",
        autoStartBot                    = "AutoStartBot",
        combatMovement                  = "EnableCombatMovement",
        enableEvents                    = "EnableEvents",
        enableRepair                    = "EnableRepair",
        ignoreLevelMarker               = "IgnoreLevelMarker",
        wpVendor                        = "UseWPForVendor",
        wpEvents                        = "UseWPForEvents",
        enableUnstuck                   = "EnableUnstuck",
        unstuckCount                    = "UnstuckExitCount",
        eventTimeout                    = "EventTimeout",
        blacklistEvent                  = "BlacklistEvent",
        prioEvent                       = "Events>Aggro",
        prioRevive                      = "Revive>Aggro",
        vendorRarity                    = "MaxItemSellRarity",
        sellWeapon                      = "SellWeapons",
        sellArmor                       = "SellArmor",
        sellTrinket                     = "SellTrinkets",
        sellUpgrade                     = "SellUpgradeComponents",
        sellCrafting                    = "SellCraftingMats",
        sellTrophy                      = "SellTrophies",
        enableGather                    = "EnableGathering",
        buyTools                        = "BuyGatheringTools",
        buyBestTool                     = "BuyBestTool",
        toolRarity                      = "ToolRarity",
        toolStock                       = "ToolStock",
        enableSalvage                   = "EnableSalvaging",
        buyKits                         = "BuySalvageKits",
        buyBestKit                      = "BuyBestKit",
        kitRarity                       = "KitRarity",
        kitStock                        = "KitStock",
        salvageTrophy                   = "SalvageTrophies",
        botStatus                       = "BotStatus",
        settings                        = "Settings",
        advancedSettings                = "AdvancedSettings",
        vendorSettings                  = "VendorSettings",
        salvageSettings                 = "SalvageSettings",
        gatherSettings                  = "GatherSettings",
        skipcutscene					= "Skip Cutscenes",

        -- meshmanager.lua
        meshManager                     = "MeshManager",
        queensdale                      = "Queensdale",
        harathiHinterlands              = "HarathiHinterlands",
        divinitysReach                  = "DivinitysReach",
        plainsOfAshford                 = "PlainsofAshford",
        blazeridgeSteppes               = "BlazeridgeSteppes",
        fieldsOfRuin                    = "FieldsofRuin",
        fireheartRise                   = "FireheartRise",
        kessexHills                     = "KessexHills",
        gendarranFields                 = "GendarranFields",
        ironMarches                     = "IronMarches",
        dredgehauntCliffs               = "DredgehauntCliffs",
        lornarsPass                     = "LornarsPass",
        wayfarerFoothills               = "WayfarerFoothills",
        timberlineFalls                 = "TimberlineFalls",
        frostgorgeSound                 = "FrostgorgeSound",
        snowdenDrifts                   = "SnowdenDrifts",
        diessaPlateau                   = "DiessaPlateau",
        ascalonianCatacombsStory        = "AscalonianCatacombs(Story)",
        caledonForest                   = "CaledonForest",
        metricaProvince                 = "MetricaProvince",
        ascalonianCatacombsExp          = "AscalonianCatacombs(Explo)",
        eternalBattlegrounds            = "EternalBattlegrounds",
        mountMaelstrom                  = "MountMaelstrom",
        lionsArch                       = "LionsArch",
        straightsOfDevastation          = "StraitsOfDevastation",
        sparkflyFen                     = "SparkflyFen",
        brisbanWildlands                = "BrisbanWildlands",
        cursedShore                     = "CursedShore",
        malchorsLeap                    = "MalchorsLeap",
        citadelOfFlamesStory            = "CitadelOfFlames(Story)",
        citadelOfFlamesExp              = "CitadelOfFlames(Explo)",
        bloodtideCoast                  = "BloodtideCoast",
        theGrove                        = "TheGrove",
        borderlands1                    = "BlueGreenRedBorderlands1",
        borderlands2                    = "BlueGreenRedBorderlands2",
        borderlands3                    = "BlueGreenRedBorderlands3",
        rataSum                         = "RataSum",
        blackCitadel                    = "BlackCitadel",
        hoelbrak                        = "Hoelbrak",
        southsunCove                    = "SouthsunCove",
        activated                       = "Activated",
        mapName                         = "Map",
        navmesh                         = "Navmesh",
        waypoint                        = "Waypoint",
        generalSettings                 = "GeneralSettings",
        dungeonManager                  = "DungeonManager",
        status                          = "Status",
        setPartySize                    = "Set PartySize",
        dungeons                        = "Dungeons",
        leaveDungeon                    = "Leave Dungeon",
        resetDungeon                    = "Reset Dungeon",
        stopDungeonManager              = "Stop DungeonManager",

        -- partymanager.lua
        partyManager                    = "PartyManager",
        enterCharNames                  = "Enter Character Names:",
        member1                         = "Member1",
        member2                         = "Member2",
        member3                         = "Member3",
        member4                         = "Member4",
        member5                         = "Member5",
        groupInfo                       = "GroupInfo",

        -- skillmanager.lua
        skillManager                    = "SkillManager",
        profile                         = "Profile",
		refreshProfiles                 = "Refresh Profile List",
		saveProfile                 	= "Save Current Profile",
        deleteProfile                   = "Delete Current Profile",
        newProfileName                  = "New Profile Name",
        newProfile                      = "New Profile",
        autoetectSkills                 = "Autodetect Skills",
        skillEditor                     = "Skill Editor",
        enabled                         = "Enabled",
        priority                        = "Priority",
        cooldown                        = "Cooldown",
        minRange                        = "MinRange",
        maxRange                        = "MaxRange",
        isGroundTargeted                = "IsGroundTargeted",
        targetType                      = "TargetType",
        useInCombat                     = "UseInCombat",
        playerMoving                    = "Player Moving",
        playerHPGT                      = "Player HP% >",
        playerHPLT                      = "Player HP% <",
        playerPowerGT                   = "Player Power% >",
        playerPowerLT                   = "Player Power% <",
        playerHas                       = "Player has ",
        orPlayerHas                     = "or Player has ",
        playerHasNot                    = "Player has NOT ",
        orPlayerHasNot                  = "or Player has NOT ",
        targetMoving                    = "Target Moving",
        targetHPGT                      = "Target HP% >",
        targetHPLT                      = "Target HP% <",
        targetDistanceGT                = "Target Distance >",
        targetDistanceLT                = "Target Distance <",
        enemiesNearCount                = "Enemies Near Target(Count) >=",
        enemiesNearRange                = "Enemies Near Target(MaxRange) =",
        alliesNearCount                 = "Allies Near Target(Count) >=",
        alliesNearRange                 = "Allies Near Target(MaxRange) =",
        targetHas                       = "Target has ",
        orTargetHas                     = "or Target has ",
        targetHasNot                    = "Target has NOT ",
        orTargetHasNot                  = "or Target has NOT ",

        -- leader.lua
        browserStats                    = "Enable BrowserStats",
        groupBotting                    = "Enable Groupbotting",
        serverIP                        = "MultiBotComServer IP",
        serverPort                      = "MultiBotComServer Port",
        serverPW                        = "MultiBotComServer Password",
        groupBotting                    = "GroupBotting",

        -- salvaging.lua
        rarityJunk                      = "Junk",
        rarityCommon                    = "Common",
        rarityFine                      = "Fine",
        rarityMasterwork                = "Masterwork",
        rarityRare                      = "Rare",
        rarityExotic                    = "Exotic",
        salvage                         = "Salvage ",
        enableSalvage                   = "EnableSalvage",

        -- common profession
        allowedRange                    = "Allowed Range [0-100], 0=Disabled",
        skill7HP                        = "Use Skill7 at HP%",
        skill8HP                        = "Use Skill8 at HP%",
        skill9HP                        = "Use Skill9 at HP%",
        eliteHP                         = "Use Elite  at HP%",
        autoF1                          = "AutoUse F1",
        autoF2                          = "AutoUse F2",
        autoF3                          = "AutoUse F3",

        -- elementalist.lua
        autoSwapAttunements             = "AutoSwapAttunements",
        elementalistSettings            = "Elementalist-Settings",

        -- engineer.lua
        autoSwapToKits                  = "AutoSwapToKits",
        engineerSettings                = "Engineer-Settings",

        -- guardian.lua
        autoSwapWeaponSets              = "AutoSwapWeaponSets",
        guardianSettings                = "Guardian-Settings",

        -- mesmer.lua
        mesmerSettings                  = "Mesmer-Settings",

        -- necromancer.lua
        autoUsePets                     = "AutoUsePets",
        necromancerSettings             = "Necromancer-Settings",

        -- ranger.lua
        rangerSettings                  = "Ranger-Settings",

        -- thief.lua
        thiefSettings                   = "Thief-Settings",

        -- warrior.lua
        warriorSettings                 = "Warrior-Settings",

        -- meshassistant.lua
        maModuleName                    = "MeshAssistant",
        maMarkerInspector               = "MarkerInspector",
        maMarkerTypeNone                = "None",
        maMarkerTypeFarmSpot            = "FarmSpot",
        maMarkerTypeWaypoint            = "Waypoint",
        maMarkerTypePointOfInterest     = "PointOfInterest",
        maMarkerTypeVista               = "Vista",
        maMarkerTypeSkillPoint          = "SkillPoint",
        maMarkerTypeHeartQuest          = "HeartQuest",
        maMarkerTypeRepairVendor        = "RepairVendor",
        maStartStopAutoMeshing          = "Start / Stop Auto Meshing",
        maEditMesh                      = "Edit Mesh Mode",
        maLoadExistingMesh              = "Load Existing Mesh",
        maNewResetMesh                  = "New / Reset Mesh",
        maShowHideMesh                  = "Show / Hide Mesh",
        maVersion                       = "Version",
        maTrianglesTotal                = "# Triangles Total",
        maVerticesTotal                 = "# Vertices Total",
        maVerticesCreatedThisSession    = "# Vertices Created This Session",
        maQueueSize                     = "Queue Size",
        maOpenMarkerInspector           = "Open Marker Inspector",
        maUndoCells1                    = "Undo 100 Cells (+stop)",
        maUndoCells2                    = "Undo 500 Cells (+stop)",
        maUndoCells3                    = "Undo 1000 Cells (+stop)",
        maToggleSteepSettings           = "Toggle Steep Settings",
        maToggleWideSettings            = "Toggle Wide Settings",
        maHideUnselectedVertices        = "Hide Unselected Vertices",
        maUseQueue                      = "Use Queue",
        maUpdateInterval                = "Update Interval",
        maNormalDistance                = "Normal Distance",
        maForceWideAreaDistance         = "Force Wide Area Distance",
        maForceRadiusNormal             = "Force Radius Normal",
        maForceRadiusWide               = "Force Radius Wide",
        maForceCellDistance             = "Force Cell Distance",
        maQueueElementsPerTick          = "Queue Elements Per Tick",
        maQueueElementsPerTickInc       = "Queue Elements Per Tick Increments",
        maAngleThreshold                = "Angle Threshold",
        maCellWidth                     = "Cell Width",
        maSingleZThresholdNormal        = "Single Height Threshold Normal",
        maSingleZThresholdSteep         = "Single Height Threshold Steep",
        maHeightThresholdHigh           = "High Hight Threshold",
        maHeightThresholdLow            = "Low Hight Threshold",
        maPointGridDistance             = "Cloud Point Distance",
        maGroupInfo                     = "Info",
        maGroupToolbox                  = "Toolbox",
        maGroupInputSettings            = "Input Settings",
        maGroupDisplaySettings          = "Display Settings",
        maGroupBasicSettings            = "Basic Settings",
        maGroupAdvancedSettings         = "Advanced Settings",
        maGroupExpertSettings           = "Expert Settings",
        maMarkerID                      = "ID",
        maMarkerName                    = "Name",
        maMarkerType                    = "Type",
        maMarkerMinLevel                = "Minimum Level",
        maMarkerMaxLevel                = "Maximum Level",
        maMarkerDeleteMarker            = "Delete Marker",
        maMarkerSelectToEdit            = "Select To Edit",
        maMarkerNewName                 = "NewMarker",
        maMarkerGroupDetails            = "Details",
        maMarkerGroupAllMarkers         = "All Markers",
        maDontTouchLoadedMesh           = "Don't Touch Loaded Mesh",
        maEdgeHitCheckPoints            = "Edge Hit Check Points",
        maMeshWaterSurfaces             = "Mesh Water Surface",
        maDisableShowDebugMessages      = "Disable Debug Console Messages"
    },
    ["cn"] =
        {
        -- gw2.lua
        startStop                       = "StartStop",
        doPulse                         = "Pulse(Debug)",
        pulseTime                       = "Pulse Time (ms)",
        enableLog                       = "Enable Log",
        task                            = "Task",
        state                           = "State",
        effect                          = "Effect",
        autoStartBot                    = "AutoStartBot",
        combatMovement                  = "EnableCombatMovement",
        enableEvents                    = "EnableEvents",
        enableRepair                    = "EnableRepair",
        ignoreLevelMarker               = "IgnoreLevelMarker",
        wpVendor                        = "UseWPForVendor",
        wpEvents                        = "UseWPForEvents",
        enableUnstuck                   = "EnableUnstuck",
        unstuckCount                    = "UnstuckExitCount",
        eventTimeout                    = "EventTimeout",
        blacklistEvent                  = "BlacklistEvent",
        prioEvent                       = "Events>Aggro",
        prioRevive                      = "Revive>Aggro",
        vendorRarity                    = "MaxItemSellRarity",
        sellWeapon                      = "SellWeapons",
        sellArmor                       = "SellArmor",
        sellTrinket                     = "SellTrinkets",
        sellUpgrade                     = "SellUpgradeComponents",
        sellCrafting                    = "SellCraftingMats",
        sellTrophy                      = "SellTrophies",
        enableGather                    = "EnableGathering",
        buyTools                        = "BuyGatheringTools",
        buyBestTool                     = "BuyBestTool",
        toolRarity                      = "ToolRarity",
        toolStock                       = "ToolStock",
        enableSalvage                   = "EnableSalvaging",
        buyKits                         = "BuySalvageKits",
        buyBestKit                      = "BuyBestKit",
        kitRarity                       = "KitRarity",
        kitStock                        = "KitStock",
        salvageTrophy                   = "SalvageTrophies",
        botStatus                       = "BotStatus",
        settings                        = "Settings",
        advancedSettings                = "AdvancedSettings",
        vendorSettings                  = "VendorSettings",
        salvageSettings                 = "SalvageSettings",
        gatherSettings                  = "GatherSettings",
        skipcutscene					= "Skip Cutscenes",

        -- meshmanager.lua
        meshManager                     = "网格脚本管理器",
        queensdale                      = "Queensdale",
        harathiHinterlands              = "HarathiHinterlands",
        divinitysReach                  = "DivinitysReach",
        plainsOfAshford                 = "PlainsofAshford",
        blazeridgeSteppes               = "BlazeridgeSteppes",
        fieldsOfRuin                    = "FieldsofRuin",
        fireheartRise                   = "FireheartRise",
        kessexHills                     = "KessexHills",
        gendarranFields                 = "GendarranFields",
        ironMarches                     = "IronMarches",
        dredgehauntCliffs               = "DredgehauntCliffs",
        lornarsPass                     = "LornarsPass",
        wayfarerFoothills               = "WayfarerFoothills",
        timberlineFalls                 = "TimberlineFalls",
        frostgorgeSound                 = "FrostgorgeSound",
        snowdenDrifts                   = "SnowdenDrifts",
        diessaPlateau                   = "DiessaPlateau",
        ascalonianCatacombsStory        = "AscalonianCatacombs(Story)",
        caledonForest                   = "CaledonForest",
        metricaProvince                 = "MetricaProvince",
        ascalonianCatacombsExp          = "AscalonianCatacombs(Explo)",
        eternalBattlegrounds            = "EternalBattlegrounds",
        mountMaelstrom                  = "MountMaelstrom",
        lionsArch                       = "LionsArch",
        straightsOfDevastation          = "StraitsOfDevastation",
        sparkflyFen                     = "SparkflyFen",
        brisbanWildlands                = "BrisbanWildlands",
        cursedShore                     = "CursedShore",
        malchorsLeap                    = "MalchorsLeap",
        citadelOfFlamesStory            = "CitadelOfFlames(Story)",
        citadelOfFlamesExp              = "CitadelOfFlames(Explo)",
        bloodtideCoast                  = "BloodtideCoast",
        theGrove                        = "TheGrove",
        borderlands1                    = "BlueGreenRedBorderlands1",
        borderlands2                    = "BlueGreenRedBorderlands2",
        borderlands3                    = "BlueGreenRedBorderlands3",
        rataSum                         = "RataSum",
        blackCitadel                    = "BlackCitadel",
        hoelbrak                        = "Hoelbrak",
        southsunCove                    = "SouthsunCove",
        activated                       = "Activated",
        mapName                         = "Map",
        navmesh                         = "Navmesh",
        waypoint                        = "Waypoint",
        generalSettings                 = "GeneralSettings",
        dungeonManager                  = "副本管理器",
        status                          = "Status",
        setPartySize                    = "Set PartySize",
        dungeons                        = "Dungeons",
        leaveDungeon                    = "Leave Dungeon",
        resetDungeon                    = "Reset Dungeon",
        stopDungeonManager              = "Stop DungeonManager",

        -- partymanager.lua
        partyManager                    = "组队管理器",
        enterCharNames                  = "Enter Character Names:",
        member1                         = "Member1",
        member2                         = "Member2",
        member3                         = "Member3",
        member4                         = "Member4",
        member5                         = "Member5",
        groupInfo                       = "GroupInfo",

        -- skillmanager.lua
        skillManager                    = "SkillManager",
        profile                         = "Profile",
		refreshProfiles                 = "Refresh Profile List",
		saveProfile                 	= "Save Current Profile",
        deleteProfile                   = "Delete Current Profile",
        newProfileName                  = "New Profile Name",
        newProfile                      = "New Profile",
        autoetectSkills                 = "Autodetect Skills",
        skillEditor                     = "Skill Editor",
        enabled                         = "Enabled",
        priority                        = "Priority",
        cooldown                        = "Cooldown",
        minRange                        = "MinRange",
        maxRange                        = "MaxRange",
        isGroundTargeted                = "IsGroundTargeted",
        targetType                      = "TargetType",
        useInCombat                     = "UseInCombat",
        playerMoving                    = "Player Moving",
        playerHPGT                      = "Player HP% >",
        playerHPLT                      = "Player HP% <",
        playerPowerGT                   = "Player Power% >",
        playerPowerLT                   = "Player Power% <",
        playerHas                       = "Player has ",
        orPlayerHas                     = "or Player has ",
		orPlayerCond					= "Player has #Conditions >",
        playerHasNot                    = "Player has NOT ",
        orPlayerHasNot                  = "or Player has NOT ",
        targetMoving                    = "Target Moving",
        targetHPGT                      = "Target HP% >",
        targetHPLT                      = "Target HP% <",
        targetDistanceGT                = "Target Distance >",
        targetDistanceLT                = "Target Distance <",
        enemiesNearCount                = "Enemies Near Target(Count) >=",
        enemiesNearRange                = "Enemies Near Target(MaxRange) =",
        alliesNearCount                 = "Allies Near Target(Count) >=",
        alliesNearRange                 = "Allies Near Target(MaxRange) =",
        targetHas                       = "Target has ",
        orTargetHas                     = "or Target has ",
        targetHasNot                    = "Target has NOT ",
        orTargetHasNot                  = "or Target has NOT ",

        -- leader.lua
        browserStats                    = "Enable BrowserStats",
        groupBotting                    = "Enable Groupbotting",
        serverIP                        = "MultiBotComServer IP",
        serverPort                      = "MultiBotComServer Port",
        serverPW                        = "MultiBotComServer Password",
        groupBotting                    = "GroupBotting",

        -- salvaging.lua
        rarityJunk                      = "Junk",
        rarityCommon                    = "Common",
        rarityFine                      = "Fine",
        rarityMasterwork                = "Masterwork",
        rarityRare                      = "Rare",
        rarityExotic                    = "Exotic",
        salvage                         = "Salvage ",
        enableSalvage                   = "EnableSalvage",

        -- common profession
        allowedRange                    = "Allowed Range [0-100], 0=Disabled",
        skill7HP                        = "Use Skill7 at HP%",
        skill8HP                        = "Use Skill8 at HP%",
        skill9HP                        = "Use Skill9 at HP%",
        eliteHP                         = "Use Elite  at HP%",
        autoF1                          = "AutoUse F1",
        autoF2                          = "AutoUse F2",
        autoF3                          = "AutoUse F3",

        -- elementalist.lua
        autoSwapAttunements             = "AutoSwapAttunements",
        elementalistSettings            = "Elementalist-Settings",

        -- engineer.lua
        autoSwapToKits                  = "AutoSwapToKits",
        engineerSettings                = "Engineer-Settings",

        -- guardian.lua
        autoSwapWeaponSets              = "AutoSwapWeaponSets",
        guardianSettings                = "Guardian-Settings",

        -- mesmer.lua
        mesmerSettings                  = "Mesmer-Settings",

        -- necromancer.lua
        autoUsePets                     = "AutoUsePets",
        necromancerSettings             = "Necromancer-Settings",

        -- ranger.lua
        rangerSettings                  = "Ranger-Settings",

        -- thief.lua
        thiefSettings                   = "Thief-Settings",

        -- warrior.lua
        warriorSettings                 = "Warrior-Settings",

        -- meshassistant.lua
        maModuleName                    = "MeshAssistant",
        maMarkerInspector               = "MarkerInspector",
        maMarkerTypeNone                = "None",
        maMarkerTypeFarmSpot            = "FarmSpot",
        maMarkerTypeWaypoint            = "Waypoint",
        maMarkerTypePointOfInterest     = "PointOfInterest",
        maMarkerTypeVista               = "Vista",
        maMarkerTypeSkillPoint          = "SkillPoint",
        maMarkerTypeHeartQuest          = "HeartQuest",
        maMarkerTypeRepairVendor        = "RepairVendor",
        maStartStopAutoMeshing          = "Start / Stop Auto Meshing",
        maEditMesh                      = "Edit Mesh Mode",
        maLoadExistingMesh              = "Load Existing Mesh",
        maNewResetMesh                  = "New / Reset Mesh",
        maShowHideMesh                  = "Show / Hide Mesh",
        maVersion                       = "Version",
        maTrianglesTotal                = "# Triangles Total",
        maVerticesTotal                 = "# Vertices Total",
        maVerticesCreatedThisSession    = "# Vertices Created This Session",
        maQueueSize                     = "Queue Size",
        maOpenMarkerInspector           = "Open Marker Inspector",
        maUndoCells1                    = "Undo 100 Cells (+stop)",
        maUndoCells2                    = "Undo 500 Cells (+stop)",
        maUndoCells3                    = "Undo 1000 Cells (+stop)",
        maToggleSteepSettings           = "Toggle Steep Settings",
        maToggleWideSettings            = "Toggle Wide Settings",
        maHideUnselectedVertices        = "Hide Unselected Vertices",
        maUseQueue                      = "Use Queue",
        maUpdateInterval                = "Update Interval",
        maNormalDistance                = "Normal Distance",
        maForceWideAreaDistance         = "Force Wide Area Distance",
        maForceRadiusNormal             = "Force Radius Normal",
        maForceRadiusWide               = "Force Radius Wide",
        maForceCellDistance             = "Force Cell Distance",
        maQueueElementsPerTick          = "Queue Elements Per Tick",
        maQueueElementsPerTickInc       = "Queue Elements Per Tick Increments",
        maAngleThreshold                = "Angle Threshold",
        maCellWidth                     = "Cell Width",
        maSingleZThresholdNormal        = "Single Height Threshold Normal",
        maSingleZThresholdSteep         = "Single Height Threshold Steep",
        maHeightThresholdHigh           = "High Hight Threshold",
        maHeightThresholdLow            = "Low Hight Threshold",
        maPointGridDistance             = "Cloud Point Distance",
        maGroupInfo                     = "Info",
        maGroupToolbox                  = "Toolbox",
        maGroupInputSettings            = "Input Settings",
        maGroupDisplaySettings          = "Display Settings",
        maGroupBasicSettings            = "Basic Settings",
        maGroupAdvancedSettings         = "Advanced Settings",
        maGroupExpertSettings           = "Expert Settings",
        maMarkerID                      = "ID",
        maMarkerName                    = "Name",
        maMarkerType                    = "Type",
        maMarkerMinLevel                = "Minimum Level",
        maMarkerMaxLevel                = "Maximum Level",
        maMarkerDeleteMarker            = "Delete Marker",
        maMarkerSelectToEdit            = "Select To Edit",
        maMarkerNewName                 = "NewMarker",
        maMarkerGroupDetails            = "Details",
        maMarkerGroupAllMarkers         = "All Markers",
        maDontTouchLoadedMesh           = "Don't Touch Loaded Mesh",
        maEdgeHitCheckPoints            = "Edge Hit Check Points",
        maMeshWaterSurfaces             = "Mesh Water Surface",
        maDisableShowDebugMessages      = "Disable Debug Console Messages"
    }
}

function SetLanguage(event, arg)
	d(tostring(arg))
end

-- returns a string in the current language or an indicator that the string does not exist in the language file
function GetString(stringName)
	if strings[gCurrentLanguage][stringName] == nil then
		return "%" .. tostring(stringName) .. "%"
	else
		return strings[gCurrentLanguage][stringName]
	end
end

RegisterEventHandler("GW2MINION.setlanguage", SetLanguage)
