GW2MINION_raw = 
{
	["Mesh_[1-15]AshfordPlains"] = "1",
	["Mesh_[25-40]Gendarran Fields"] = "1",
	["Mesh_[75-80]Cursed Shore"] = "1",
	["Mesh_[80 FARM] Malchors Sprung V1.1"] = "1",
	Mesh_cs_chain_abob = "1",
	["Mesh_mahlstromgipfel 1.4"] = "1",
	TargetWaypointID = 796,
	gAutoUsePets = "1",
	gAutostartbot = "1",
	gCombatmovement = "1",
	gEleSK10 = "90",
	gEleSK7 = "87",
	gEleSK8 = "99",
	gEleSK9 = "99",
	gEleSwap = "1",
	gEnableLog = "1",
	gEnableRepair = "1",
	gEngSK10 = "99",
	gEngSK7 = "99",
	gEngSK8 = "99",
	gEngSK9 = "99",
	gEngSwapWeapons = "1",
	gGW2MinionPulseTime = "150",
	gGuardF1 = "1",
	gGuardF2 = "1",
	gGuardF3 = "1",
	gGuardSK10 = "15",
	gGuardSK7 = "80",
	gGuardSK8 = "60",
	gGuardSK9 = "94",
	gGuardSwapWeapons = "1",
	gIP = "127.0.0.1",
	gIgnoreMarkerCap = "1",
	gLeaderID = 2390,
	gLeaderIndex = "0",
	gLeaderMapID = 62,
	gMaxItemSellRarity = "3",
	gMaxSalvageRarity = "2",
	gMesSK10 = "95",
	gMesSK7 = "95",
	gMesSK8 = "95",
	gMesSK9 = "95",
	gMesSwapWeapons = "1",
	gMinionEnabled = "1",
	gMinionstick = "1",
	gNavSwitchEnabled = "1",
	gNavSwitchTime = "5",
	gNecSK10 = "30",
	gNecSK7 = "85",
	gNecSK8 = "85",
	gNecSK9 = "85",
	gNecroSwapWeapons = "1",
	gPort = "7777",
	gPw = "mypw",
	gStats_enabled = "0",
	gUseWaypoints = "0",
	gVendor_Armor = "1",
	gVendor_CraftingMats = "0",
	gVendor_Junk = "1",
	gVendor_Repair = "0",
	gVendor_Trinkets = "1",
	gVendor_Trophies = "0",
	gVendor_UpgradeComps = "1",
	gVendor_Weapons = "1",
	gWarSK10 = "96",
	gWarSK7 = "90",
	gWarSK8 = "80",
	gWarSK9 = "70",
	gWarSwapWeapons = "1",
	gWarUseBurst = "1",
	gdoEvents = "1",
	salvagesettings = 
	{
		
		{
			desc = "Common",
			salvage = "1",
		},
		
		{
			desc = "Fine",
			salvage = "1",
		},
		
		{
			desc = "Masterwork",
			salvage = "1",
		},
		
		{
			desc = "Rare",
			salvage = "0",
		},
		
		{
			desc = "Exotic",
			salvage = "0",
		},
		
		{
			desc = "Legendary",
			salvage = "0",
		},
	},
	version = 1.4,
}



