-- BIG THANKS TO Inktrocity for this list!!!

 wt_core_mapdata = {
     
            --*************************************************************************************************************
            -- Cities
            --*************************************************************************************************************
           
            [218] = { --Black Citadel
                    poi = {
                            [827] = { name = "Ash Tribune Quarters" },
                            [828] = { name = "Blood Tribune Quarters" },
                            [829] = { name = "Farhar of Young Heroes" },
                            [830] = { name = "Abandoned Caverns (Access Prohibited)" },
                            [831] = { name = "Iron Tribune Quarters" },
                            [832] = { name = "Durmand Scriptorium" },
                            [833] = { name = "Vigil Chapterhouse" },
                            [834] = { name = "Serrated Blade Tavern" },
                            [924] = { name = "Ash Checkpoint 13" },
                            [925] = { name = "Hero\'s Forum" },
                            [926] = { name = "20th Blood Cohort" },
                            [927] = { name = "Ashford Gate" },
                            [928] = { name = "12th Iron Maniple" },
                            [929] = { name = "Citadel Stockade" },
                            [930] = { name = "Storm Caller Triumph" },
                            [931] = { name = "The War Council" },
                            [1140] = { name = "Plaza of Remembrance" },
                    },
                    waypoint = {
                            [932] = { name = "Gladium Waypoint" },
                            [933] = { name = "Mustering Ground Waypoint" },
                            [934] = { name = "Memorial Waypoint" },
                            [935] = { name = "Factorium Waypoint" },
                            [936] = { name = "Diessa Gate Waypoint" },
                            [937] = { name = "Ligacus Aquilo Waypoint" },
                            [938] = { name = "Bane Waypoint" },
                            [939] = { name = "Hero\'s Waypoint" },
                            [940] = { name = "Ruins of Rin Waypoint" },
                            [941] = { name = "Imperator\'s Waypoint" },
                            [1079] = { name = "Junker\'s Waypoint" },
                    },
            },
           
            [18] = { --Divinity\'s Reach
                    poi = {
                            [253] = { name = "Shrine of the Six" },
                            [254] = { name = "Seraph Headquarters" },
                            [255] = { name = "Queen\'s Throne Room" },
                            [256] = { name = "Mina\'s Target Shooting" },
                            [257] = { name = "Durmand Hall" },
                            [258] = { name = "Maiden\'s Whisper" },
                            [259] = { name = "Uzolan\'s Mechanical Orchestra" },
                            [260] = { name = "Vigil Hall" },
                            [261] = { name = "Vanguard Hospital" },
                            [262] = { name = "Queen\'s Heart Orphanage" },
                            [263] = { name = "Minister Zamon\'s Mansion" },
                            [264] = { name = "Minister Wi\'s Mansion" },
                            [265] = { name = "Chamber of Ministers" },
                            [266] = { name = "Manor Hill" },
                            [267] = { name = "Cottage Bend" },
                            [268] = { name = "Rook\'s Row" },
                            [269] = { name = "Haidryn\'s Menagerie" },
                            [270] = { name = "Central Plaza" },
                            [817] = { name = "Skull Plaza" },
                            [843] = { name = "The Busted Flagon" },
                    },
                    waypoint = {
                            [803] = { name = "Dwayna Waypoint" },
                            [804] = { name = "Grenth Waypoint" },
                            [805] = { name = "Kormir Waypoint" },
                            [806] = { name = "Lyssa Waypoint" },
                            [807] = { name = "Melandru Waypoint" },
                            [808] = { name = "Balthazar Waypoint" },
                            [809] = { name = "Palace Waypoint" },
                            [810] = { name = "Commons Waypoint" },
                            [811] = { name = "Rurikton Waypoint" },
                            [812] = { name = "Collapse Waypoint" },
                            [813] = { name = "Ossan Waypoint" },
                            [814] = { name = "Salma Waypoint" },
                            [1278] = { name = "Ministers Waypoint" },
                    },
            },
           
            [326] = { --Hoelbrak
                    poi = {
                            [881] = { name = "Courage Brewery" },
                            [882] = { name = "Fang of the Serpent" },
                            [883] = { name = "Brawler\'s Bout" },
                            [884] = { name = "The Great Rise" },
                            [885] = { name = "Skarti\'s Steading" },
                            [886] = { name = "Stonewright\'s Steading" },
                            [887] = { name = "Sigfast\'s Steading" },
                            [888] = { name = "Master Blackforge\'s Steading" },
                            [889] = { name = "Old Fiach\'s Lorestead" },
                            [890] = { name = "Boasting Hall" },
                            [891] = { name = "Hrothbeir\'s Rest" },
                            [892] = { name = "Vheratha\'s Tavern" },
                            [893] = { name = "Priory Encampment" },
                            [894] = { name = "Dragon Hallow" },
                            [895] = { name = "Vigil Billet" },
                            [896] = { name = "Lost Spirits\' Hallow" },
                            [897] = { name = "Bear Hallow" },
                            [898] = { name = "Wolf Hallow" },
                            [899] = { name = "Raven Hallow" },
                            [900] = { name = "Snow Leopard Hallow" },
                            [952] = { name = "Knut Whitebear\'s Loft" },
                            [1135] = { name = "Traveler\'s Loft" },
                            [1136] = { name = "Bilrost Gallery" },
                            [1263] = { name = "Raven Hearth" },
                    },
                    waypoint = {
                            [901] = { name = "Might and Main Waypoint" },
                            [902] = { name = "Trade Commons Waypoint" },
                            [903] = { name = "Snow Leopard Waypoint" },
                            [904] = { name = "Raven Waypoint" },
                            [905] = { name = "Bear Waypoint" },
                            [906] = { name = "Wolf Waypoint" },
                            [907] = { name = "Shelter Rock Waypoint" },
                            [908] = { name = "Legends Waypoint" },
                            [909] = { name = "Eastern Watchpost Waypoint" },
                            [910] = { name = "Southern Watchpost Waypoint" },
                            [911] = { name = "Peeta\'s Waypoint" },
                            [912] = { name = "Hero\'s Compass Waypoint" },
                            [981] = { name = "Great Lodge Waypoint" },
                            [1288] = { name = "Upper Balcony Waypoint" },
                    },
            },
           
            [50] = { --Lion\'s Arch
                    poi = {
                            [1052] = { name = "Old Lion\'s Arch" },
                            [1053] = { name = "Main Haven Headquarters" },
                            [1054] = { name = "Commodore\'s Manor" },
                            [1055] = { name = "Crow\'s Nest Tavern (Captain\'s Council)" },
                            [1056] = { name = "Coriolis Plaza" },
                            [1057] = { name = "Mystic Plaza" },
                            [1058] = { name = "Deverol Island" },
                            [1059] = { name = "Lion\'s Gate" },
                            [1060] = { name = "Tokk\'s Mill" },
                            [1061] = { name = "The Gangplank" },
                            [1062] = { name = "Lost Grotto" },
                            [1063] = { name = "Durmand Dig Site" },
                            [1064] = { name = "The Undermarket" },
                            [1065] = { name = "Lion\'s Court" },
                            [1066] = { name = "Shuttered Gate" },
                            [1067] = { name = "Vigil Centerhouse" },
                            [1068] = { name = "Tenanera\'s Pit" },
                            [1189] = { name = "Moran Memorial" },
                            [1190] = { name = "Moorookoo Village" },
                            [1284] = { name = "Yomm\'s Merchantile" },
                            [1459] = { name = "Black Lion Trading Company HQ" },
                            [1758] = { name = "Macha\'s Landing" },
                            [1759] = { name = "Consortium Gift Shop" },
                    },
                    waypoint = {
                            [1036] = { name = "Canal Ward Waypoint" },
                            [1037] = { name = "Smuggler\'s Waypoint" },
                            [1038] = { name = "Bloodcoast Ward Waypoint" },
                            [1039] = { name = "Claw Island Portage Waypoint" },
                            [1040] = { name = "Trader\'s Forum Waypoint" },
                            [1041] = { name = "Gate Hub Plaza Waypoint" },
                            [1069] = { name = "Diverse Ledges Waypoint" },
                            [1070] = { name = "Western Ward Waypoint" },
                            [1071] = { name = "Sanctum Harbor Waypoint" },
                            [1072] = { name = "Fort Marriner Waypoint" },
                            [1073] = { name = "Eastern Ward Waypoint" },
                            [1074] = { name = "Lion\'s Shadow Inn Waypoint" },
                            [1075] = { name = "Farshore Waypoint" },
                    },
            },
           
            [139] = { --Rata Sum
                    poi = {
                            [1168] = { name = "Dept. of Arcane Eye" },
                            [1169] = { name = "Polymock Atrium" },
                            [1170] = { name = "Arcane Council" },
                            [1171] = { name = "PR-1000 Prototype Golem" },
                            [1172] = { name = "Inquest Recruiting Station" },
                            [1173] = { name = "Peacemakers Headquarters" },
                            [1174] = { name = "Priory Recruiting Station" },
                            [1175] = { name = "The Magihedron" },
                            [1176] = { name = "Forge Hall" },
                            [1177] = { name = "Thamaturgic Calculus" },
                            [1178] = { name = "Skinner Hall" },
                            [1179] = { name = "Vigil Recruiting Station" },
                            [1180] = { name = "The Aquatarium" },
                            [1181] = { name = "Engaged Demo Station" },
                            [1182] = { name = "Zojja\'s Workstation (Don\'t Touch!)" },
                            [1183] = { name = "Usability Station" },
                            [1184] = { name = "Artisan Hall" },
                            [1285] = { name = "Antidawn Anchorage" },
                            [1286] = { name = "Dawnside Quay" },
                    },
                    waypoint = {
                            [1043] = { name = "Metrical Court Waypoint" },
                            [1044] = { name = "Magustan Court Waypoint" },
                            [1204] = { name = "Magicat Court Waypoint" },
                            [1205] = { name = "Incubation Waypoint" },
                            [1206] = { name = "Accountancy Waypoint" },
                            [1207] = { name = "Apprentice Waypoint" },
                            [1208] = { name = "Research Waypoint" },
                            [1209] = { name = "Auxiliary Waypoint" },
                            [1287] = { name = "Port Waypoint" },
                    },
            },
           
            [91] = { --The Grove
                    poi = {
                            [1141] = { name = "The House of Aife" },
                            [1142] = { name = "The House of Kahedins" },
                            [1143] = { name = "The House of Riannoc" },
                            [1144] = { name = "The House of Caithe" },
                            [1145] = { name = "The House of Malomedies" },
                            [1146] = { name = "The House of Niamh" },
                            [1147] = { name = "The Hidden Shelter" },
                            [1148] = { name = "Starbower Nursery" },
                            [1149] = { name = "Durmand Posting" },
                            [1150] = { name = "Vigil Shelter" },
                            [1151] = { name = "The Soul of the Pale Tree" },
                            [1152] = { name = "Gardenroot Tunnel" },
                            [1153] = { name = "Backroot Tunnel" },
                            [1154] = { name = "The Centaur\'s Path" },
                            [1155] = { name = "Pale Tree\'s Circle" },
                            [1156] = { name = "Warden\'s Watchgate" },
                            [1157] = { name = "The Envoy\'s Shelter" },
                            [1158] = { name = "The Maker\'s Path" },
                            [1159] = { name = "Ventari\'s Tablet" },
                    },
                    waypoint = {
                            [1042] = { name = "Caledon Waypoint" },
                            [1210] = { name = "Upper Commons Waypoint" },
                            [1211] = { name = "Reckoner\'s Waypoint" },
                            [1212] = { name = "Ronan\'s Waypoint" },
                    },
            },
           
            --*************************************************************************************************************
            -- Tyria
            --*************************************************************************************************************
           
            [20] = { --Blazeridge Steppes
                    poi = {
                            [496] = { name = "Tail of the Star God" },
                            [497] = { name = "Ferrusatos Village" },
                            [498] = { name = "Sootpan Kraal" },
                            [499] = { name = "Behemian Grand Kraal" },
                            [500] = { name = "Griffonclaw Peak" },
                            [501] = { name = "Skara Braevus" },
                            [502] = { name = "Wreckage of Serenity" },
                            [503] = { name = "Craze\'s Folly" },
                            [504] = { name = "Foewatch Encampment" },
                            [852] = { name = "Drake Hollow" },
                    },
                    waypoint = {
                            [505] = { name = "The Last Whiskey Bar Waypoint" },
                            [506] = { name = "Steeleye Waypoint" },
                            [507] = { name = "Tumok\'s Waypoint" },
                            [508] = { name = "Twin Sisters Waypoint" },
                            [509] = { name = "Behem Waypoint" },
                            [510] = { name = "Expanse Waypoint" },
                            [511] = { name = "Guardian Stone Waypoint" },
                            [512] = { name = "Lunk Kraal Waypoint" },
                            [513] = { name = "Terra Carorunda Waypoint" },
                            [514] = { name = "Brokentooth Waypoint" },
                            [515] = { name = "Kindling Waypoint" },
                            [516] = { name = "Brandview Waypoint" },
                            [517] = { name = "Refuge Sanctum Waypoint" },
                            [846] = { name = "Lowland Burns Waypoint" },
                            [847] = { name = "Gastor Gullet Waypoint" },
                            [848] = { name = "Kinar Fort Waypoint" },
                            [849] = { name = "Splintercrest Fort Waypoint" },
                            [850] = { name = "Soot Road Waypoint" },
                    },
            },
           
            [32] = { --Diessa Plateau
                    poi = {
                            [271] = { name = "Caravan Wreckage" },
                            [272] = { name = "Bovarin Estate" },
                            [273] = { name = "Grendich Ruins" },
                            [274] = { name = "Dunrock Gulch" },
                            [275] = { name = "Ritual Isle" },
                            [276] = { name = "Burntfur\'s Pool" },
                            [277] = { name = "Raintimber Mill" },
                            [278] = { name = "Stonefall Estate" },
                            [279] = { name = "Old Holtimm Abbey" },
                            [417] = { name = "Silex Castrum" },
                            [418] = { name = "Phasma Castrum" },
                            [944] = { name = "Camp Althea" },
                            [987] = { name = "Moorwatch Tower" },
                            [988] = { name = "Ebonshore Plant" },
                            [1033] = { name = "Butcher\'s Yard" },
                            [1627] = { name = "Old Grendich Aqueduct" },
                            [1793] = { name = "North Nolan Hatchery" },
                    },
                    waypoint = {
                            [217] = { name = "Charrgate Haven Waypoint" },
                            [218] = { name = "Blasted Moors Waypoint" },
                            [219] = { name = "Bloodsaw Mill Waypoint" },
                            [220] = { name = "Font of Rhand Waypoint" },
                            [221] = { name = "Nageling Waypoint" },
                            [222] = { name = "Nolan Waypoint" },
                            [350] = { name = "Oldgate Waypoint" },
                            [351] = { name = "Butcher\'s Block Waypoint" },
                            [352] = { name = "Charradis Estate Waypoint" },
                            [353] = { name = "Breached Wall Waypoint" },
                            [354] = { name = "Incendio Waypoint" },
                            [355] = { name = "Nemus Grove Waypoint" },
                            [356] = { name = "Breachwater Waypoint" },
                            [922] = { name = "Dawnright Estate Waypoint" },
                            [964] = { name = "Bloodcliff Waypoint" },
                            [965] = { name = "Sanctum Waypoint" },
                            [966] = { name = "Redreave Mill Waypoint" },
                            [969] = { name = "Manbane\'s Waypoint" },
                            [1090] = { name = "Blackblade Waypoint" },
                    },
            },
           
            [21] = { --Fields of Ruin
                    poi = {
                            [196] = { name = "Desert Gate" },
                            [197] = { name = "The Hawkgates" },
                            [198] = { name = "Postern Gate" },
                            [199] = { name = "Spotter\'s Base" },
                            [200] = { name = "Sapper\'s Delve" },
                            [201] = { name = "Cymbel\'s Rescue" },
                            [202] = { name = "Otyugh\'s Kraal" },
                            [203] = { name = "Wreckage of Doomspy\'s Watch" },
                            [204] = { name = "Varimhold Outpost" },
                            [205] = { name = "Ebonhawke Delegation" },
                            [206] = { name = "Summit Peak" },
                            [207] = { name = "Gillscale Pond" },
                            [208] = { name = "Delegation of the Legions" },
                            [209] = { name = "The Thunder Den" },
                            [210] = { name = "Foulbear Kraal" },
                            [1051] = { name = "The Hawke Heart" },
                            [1077] = { name = "Kestrel Market" },
                            [1078] = { name = "Defender\'s Field" },
                            [1092] = { name = "Sentinel\'s Perch" },
                            [1709] = { name = "Bloodgorge Watch Camp" },
                    },
                    waypoint = {
                            [211] = { name = "Hawkgates Waypoint" },
                            [212] = { name = "Deathblade\'s Watch Waypoint" },
                            [213] = { name = "Summit Waypoint" },
                            [214] = { name = "Tyler\'s Bivouac Waypoint" },
                            [215] = { name = "Tenaebron Waypoint" },
                            [216] = { name = "Rosko\'s Campsite Waypoint" },
                            [330] = { name = "Skoll\'s Bivouac Waypoint" },
                            [331] = { name = "Helliot Mine Waypoint" },
                            [332] = { name = "Fangfury Watch Waypoint" },
                            [333] = { name = "Vulture\'s Waypoint" },
                            [334] = { name = "Wreckage of Bloodgorge Watch Waypoint" },
                            [335] = { name = "Ogre Road Waypoint" },
                            [336] = { name = "Forlorn Gate Waypoint" },
                            [337] = { name = "Fallen Angels Garrison Waypoint" },
                            [1084] = { name = "Spotter\'s Waypoint" },
                            [1085] = { name = "Kestrel Waypoint" },
                            [1086] = { name = "Thunderbreak Waypoint" },
                    },
            },
           
            [22] = { --Fireheart Rise
                    poi = {
                            [518] = { name = "Coalpit Watchpost" },
                            [519] = { name = "Shadow Cleft" },
                            [520] = { name = "Veiled Cliff" },
                            [521] = { name = "Piketooth Tower" },
                            [522] = { name = "Gates of Flame" },
                            [523] = { name = "Termerarus Castrum" },
                            [524] = { name = "Provatum Castrum" },
                            [525] = { name = "Atrox Castrum" },
                            [526] = { name = "Noxious Castrum" },
                            [527] = { name = "Haymal Gore" },
                            [528] = { name = "Heart Speaks Not" },
                            [529] = { name = "God\'s Eye" },
                            [530] = { name = "God\'s Skull" },
                            [531] = { name = "God\'s Hand" },
                            [532] = { name = "Mangonel Bivouac" },
                            [533] = { name = "Division Shrine" },
                    },
                    waypoint = {
                            [534] = { name = "Sati Waypoint" },
                            [535] = { name = "Pig Iron Waypoint" },
                            [536] = { name = "Tuyere Command Post Waypoint" },
                            [537] = { name = "Severed Breach Waypoint" },
                            [538] = { name = "Breaktooth\'s Waypoint" },
                            [539] = { name = "Havoc Waypoint" },
                            [540] = { name = "Vidius Castrum Waypoint" },
                            [541] = { name = "Apostate Waypoint" },
                            [542] = { name = "Rustbowl Waypoint" },
                            [543] = { name = "Switchback Waypoint" },
                            [544] = { name = "Icespear\'s Waypoint" },
                            [545] = { name = "Snow Ridge Camp Waypoint" },
                            [546] = { name = "Vorgas Garrison Waypoint" },
                            [547] = { name = "Forlorn Waypoint" },
                            [548] = { name = "Senecus Castrum Waypoint" },
                            [549] = { name = "Simurgh Waypoint" },
                            [550] = { name = "Keeper\'s Waypoint" },
                            [1344] = { name = "The Flame Citadel Waypoint" },
                    },
            },
           
            [25] = { --Iron Marches
                    poi = {
                            [468] = { name = "Dewclaw Village" },
                            [469] = { name = "The Cauldron of Searing" },
                            [470] = { name = "Herdsman\'s Bastion" },
                            [471] = { name = "Bria\'s Manor" },
                            [472] = { name = "Vermin\'s Folly" },
                            [473] = { name = "Wreckage of Day\'s Labor" },
                            [474] = { name = "Invictus Castrum" },
                            [475] = { name = "Newglade Kraal" },
                            [476] = { name = "The Blasted Hearth" },
                            [477] = { name = "Grundallion\'s Lair" },
                            [478] = { name = "Fellmyst Falls" },
                            [479] = { name = "Heartsond Falls" },
                            [480] = { name = "Kilnn\'s Rest" },
                            [481] = { name = "Spentlung Depth" },
                    },
                    waypoint = {
                            [482] = { name = "Dewclaw Waypoint" },
                            [483] = { name = "Bloodfin Lake Waypoint" },
                            [484] = { name = "Old Piken Ruins Waypoint" },
                            [485] = { name = "Warhound Village Waypoint" },
                            [486] = { name = "Hellion Waypoint" },
                            [487] = { name = "Village of Scalecatch Waypoint" },
                            [488] = { name = "Sleekfur Encampment Waypoint" },
                            [489] = { name = "Brandwatch Encampment Waypoint" },
                            [490] = { name = "Viper\'s Run Waypoint" },
                            [491] = { name = "Town of Cowlfang\'s Star Waypoint" },
                            [492] = { name = "Bulwark Waypoint" },
                            [493] = { name = "Firewatch Encampment Waypoint" },
                            [494] = { name = "Gladefall Waypoint" },
                            [495] = { name = "Grostogg\'s Kraal Waypoint" },
                    },
            },
           
            [19] = { --Plains of Ashford
                    waypoint = {
                            [338] = { name = "Swordcross Outpost" },
                            [339] = { name = "Foefire\'s Heart" },
                            [340] = { name = "The Viewing Hill" },
                            [341] = { name = "Calhaan\'s Haunt" },
                            [342] = { name = "Victory Cenotaph" },
                            [343] = { name = "The Wrecking Yard" },
                            [344] = { name = "Stonecrag Kraal" },
                            [345] = { name = "Sharptail Encampment" },
                            [346] = { name = "Igni Castrum" },
                            [347] = { name = "Exterminatus HQ" },
                            [348] = { name = "Ghostsummit" },
                            [349] = { name = "Deadgod\'s Lair" },
                            [915] = { name = "Camp Keiran" },
                            [916] = { name = "Mock\'s Niche" },
                            [917] = { name = "Three Legions Court" },
                            [918] = { name = "Shards of War" },
                            [1458] = { name = "Barradin\'s Vaults" },
                    },
                    waypoint = {
                            [383] = { name = "Vir\'s Gate Waypoint" },
                            [384] = { name = "Smokestead Waypoint" },
                            [385] = { name = "Greysteel Armory Waypoint" },
                            [386] = { name = "Martyr\'s Waypoint" },
                            [387] = { name = "Temperus Point Waypoint" },
                            [388] = { name = "Ashford Waypoint" },
                            [389] = { name = "Adorea Waypoint" },
                            [390] = { name = "Ascalonian Catacombs Waypoint" },
                            [391] = { name = "Ascalon City Waypoint" },
                            [392] = { name = "Watchcrag Tower Waypoint" },
                            [393] = { name = "Duskrend Overlook Waypoint" },
                            [394] = { name = "Irondock Shipyard Waypoint" },
                            [919] = { name = "Feritas Waypoint" },
                            [920] = { name = "Guardpoint Decimus Waypoint" },
                            [921] = { name = "Spirit Hunter Camp Waypoint" },
                            [967] = { name = "Loreclaw Waypoint" },
                            [968] = { name = "Phasmatis Waypoint" },
                            [1138] = { name = "Vault Waypoint" },
                            [1784] = { name = "Langmar Estate" },
                    },
            },
           
            [73] = { --Bloodtide Coast
                    poi = {
                            [36] = { name = "Glorious Drill Collective #4" },
                            [37] = { name = "Gleaner\'s Archway" },
                            [38] = { name = "Lapatl Grounds" },
                            [39] = { name = "Aquanarium Hydropost" },
                            [40] = { name = "Stormbluff Beacon" },
                            [41] = { name = "Deadend Cave" },
                            [42] = { name = "Covington Keep" },
                            [43] = { name = "Bloody Bill\'s Base" },
                            [44] = { name = "Sullivan\'s Wake" },
                            [45] = { name = "Mudflat Camp" },
                            [46] = { name = "Vonooroovah" },
                            [47] = { name = "Morgooroo" },
                            [48] = { name = "Broken Beacon" },
                            [49] = { name = "Challdar\'s Nest" },
                            [50] = { name = "Rhiann\'s Respite" },
                            [1196] = { name = "Breekeelee" },
                            [1197] = { name = "Lorantl Grounds" },
                            [1621] = { name = "Lostwreck Passage" },
                    },
                    waypoint = {
                            [419] = { name = "Archen Foreland Waypoint" },
                            [420] = { name = "Sorrowful Waypoint" },
                            [421] = { name = "Stormbluff Waypoint" },
                            [422] = { name = "Marshwatch Haven Waypoint" },
                            [423] = { name = "Remanda Waypoint" },
                            [424] = { name = "Laughing Gull Waypoint" },
                            [425] = { name = "Barrier Camp Waypoint" },
                            [426] = { name = "Firthside Vigil Waypoint" },
                            [427] = { name = "Lostwreck Waypoint" },
                            [428] = { name = "Bogside Camp Waypoint" },
                            [429] = { name = "Mournful Waypoint" },
                            [430] = { name = "Castavall Waypoint" },
                            [431] = { name = "Jelako Waypoint" },
                            [432] = { name = "Whisperwill Waypoint" },
                            [1035] = { name = "Deadend Waypoint" },
                    },
            },
           
            [24] = { --Gendarran Fields
                    poi = {
                            [119] = { name = "Melandru\'s Cenote" },
                            [120] = { name = "Amaranth Grotto" },
                            [121] = { name = "The Beastpool" },
                            [122] = { name = "Stonefish Beach" },
                            [123] = { name = "Wiley\'s Cove" },
                            [124] = { name = "Vigil HQ" },
                            [125] = { name = "Molenheide" },
                            [126] = { name = "Almuten Mansion" },
                            [946] = { name = "Bad Omen Beach" },
                            [955] = { name = "Ambush Camp" },
                            [956] = { name = "Vollym\'s Battle Pit" },
                            [957] = { name = "Jackdaw\'s Reef" },
                            [958] = { name = "Slade\'s Bay" },
                            [1024] = { name = "Janusian Caves" },
                            [1045] = { name = "Mellaggan Shrine" },
                            [1528] = { name = "Quaggankeep Channel" },
                    },
                    waypoint = {
                            [223] = { name = "Traveler\'s Dale Waypoint" },
                            [224] = { name = "Stoneguard Gate Waypoint" },
                            [225] = { name = "Broadhollow Waypoint" },
                            [226] = { name = "Oogooth Waypoint" },
                            [227] = { name = "Cornucopian Fields Waypoint" },
                            [228] = { name = "Provern Shore Waypoint" },
                            [237] = { name = "Junction Haven Waypoint" },
                            [238] = { name = "Winter Haven Waypoint" },
                            [395] = { name = "First Haven Waypoint" },
                            [396] = { name = "Talajian Waypoint" },
                            [397] = { name = "Ascalon Settlement Waypoint" },
                            [398] = { name = "Nebo Terrace Waypoint" },
                            [399] = { name = "Blood Hill Waypoint" },
                            [400] = { name = "Northfields Waypoint" },
                            [401] = { name = "Applenook Hamlet Waypoint" },
                            [402] = { name = "Vigil Keep Waypoint" },
                            [403] = { name = "Icegate Waypoint" },
                            [404] = { name = "Almuten Waypoint" },
                            [923] = { name = "Lionbridge Waypoint" },
                            [972] = { name = "Snowblind Waypoint" },
                            [973] = { name = "Brigantine Waypoint" },
                            [1026] = { name = "Bloodfields Waypoint" },
                    },
            },
           
            [17] = { --Harathi Hinterlands
                    poi = {
                            [148] = { name = "Restricted Zone XRB" },
                            [149] = { name = "Forward Camp" },
                            [150] = { name = "Northpasture Camp" },
                            [151] = { name = "Southforge Camp" },
                            [152] = { name = "War King\'s Greatcamp" },
                            [153] = { name = "Kingsgate Camp" },
                            [154] = { name = "Watchlin Armory" },
                            [155] = { name = "Shorebluff Camp" },
                            [156] = { name = "Overwatch Camp" },
                            [157] = { name = "Confinement Camp" },
                            [158] = { name = "Blackhold Mine Camp" },
                            [159] = { name = "Drakken\'s Den" },
                            [160] = { name = "Mountainroot Lair" },
                            [161] = { name = "Koofooloo" },
                            [162] = { name = "Martyr\'s Tomb" },
                    },
                    waypoint = {
                            [165] = { name = "Faun\'s Waypoint" },
                            [166] = { name = "Shieldbluff Waypoint" },
                            [167] = { name = "Seraph\'s Landing Waypoint" },
                            [168] = { name = "Wynchona Rally Point Waypoint" },
                            [169] = { name = "Grey Gritta\'s Waypoint" },
                            [170] = { name = "Nightguard Waypoint" },
                            [171] = { name = "Demetra Waypoint" },
                            [172] = { name = "Recovery Camp Waypoint" },
                            [173] = { name = "Barricade Camp Waypoint" },
                            [174] = { name = "Trebusha\'s Overlook Waypoint" },
                            [175] = { name = "Bridgewatch Camp Waypoint" },
                            [176] = { name = "Junction Camp Waypoint" },
                            [177] = { name = "Cloven Hoof Waypoint" },
                            [178] = { name = "Arca Waypoint" },
                            [195] = { name = "Arcallion Waypoint" },
                    },
            },
           
            [23] = { --Kessex Hills
                    poi = {
                            [23] = { name = "Black Haven" },
                            [24] = { name = "Gort\'s Pit" },
                            [25] = { name = "Garenhoff" },
                            [26] = { name = "Jannaj\'s Bandits" },
                            [27] = { name = "Quarryside" },
                            [28] = { name = "Triskell Quay" },
                            [29] = { name = "Goff\'s Bandits" },
                            [30] = { name = "Kenna\'s Bandits" },
                            [31] = { name = "Auld Red Wharf" },
                            [32] = { name = "Wallwatcher Camp" },
                            [33] = { name = "Mudbay Digs" },
                            [34] = { name = "Tagotl Grounds" },
                            [35] = { name = "Krait\'s Larder" },
                            [822] = { name = "Uzolan\'s Hideout" },
                            [1270] = { name = "Barnaby\'s Watch" },
                            [1283] = { name = "Isgarren\'s View" },
                            [1526] = { name = "Lair of the Seawitch" },
                            [1527] = { name = "Mafic Core" },
                    },
                    waypoint = {
                            [3] = { name = "Fort Salma Waypoint" },
                            [4] = { name = "Overlord\'s Waypoint" },
                            [5] = { name = "Meadows Waypoint" },
                            [6] = { name = "Halacon Waypoint" },
                            [7] = { name = "Sojourner\'s Waypoint" },
                            [8] = { name = "Delanian Waypoint" },
                            [10] = { name = "Ireko Tradecamp Waypoint" },
                            [12] = { name = "Shadowheart Site Waypoint" },
                            [14] = { name = "Moogooloo Waypoint" },
                            [16] = { name = "Viathan Waypoint" },
                            [17] = { name = "Darkwound Waypoint" },
                            [18] = { name = "Cereboth Waypoint" },
                            [19] = { name = "Overlake Haven Waypoint" },
                            [20] = { name = "Kessex Haven Waypoint" },
                            [21] = { name = "Cavernhold Camp Waypoint" },
                            [22] = { name = "Greyhoof Camp Waypoint" },
                            [953] = { name = "Earthworks Camp Waypoint" },
                            [954] = { name = "Gap Waypoint" },
                    },
            },
           
            [15] = { --Queensdale
                    poi = {
                            [127] = { name = "Eda\'s Orchard" },
                            [128] = { name = "Mepi\'s Moa Ranch" },
                            [129] = { name = "Jeb\'s Wheatfield" },
                            [130] = { name = "Dalin\'s Pumping Station" },
                            [131] = { name = "Altar Brook Trading Post" },
                            [132] = { name = "Altar Brook Crossing" },
                            [133] = { name = "Hunting Lodge" },
                            [134] = { name = "Eldvin Monastery" },
                            [135] = { name = "Holdland Camp" },
                            [136] = { name = "Hidden Cliff Camp" },
                            [137] = { name = "Cliffwatch Camp" },
                            [138] = { name = "Deathroot Shack" },
                            [139] = { name = "Temple of the Ages" },
                            [140] = { name = "Righteous Hoofmoot" },
                            [835] = { name = "Bonegrinder\'s Gully" },
                            [851] = { name = "Trainer\'s Terrace" },
                            [1672] = { name = "Kappa\'s Corral" },
                            [1673] = { name = "Beetletun Waterworks" },
                            [1674] = { name = "Greatheart Weald" },
                            [1675] = { name = "Bar Curtis Ranch" },
                            [1676] = { name = "Duran Brothers\' Docks" },
                    },
                    waypoint = {
                            [239] = { name = "Shaemoor Waypoint" },
                            [240] = { name = "Fields Waypoint" },
                            [241] = { name = "Garrison Waypoint" },
                            [242] = { name = "Crossing Waypoint" },
                            [243] = { name = "Phinney Waypoint" },
                            [244] = { name = "Vale Waypoint" },
                            [245] = { name = "Heartwood Pass Camp Waypoint" },
                            [246] = { name = "Claypool Waypoint" },
                            [247] = { name = "Swamplost Haven Waypoint" },
                            [248] = { name = "Krytan Waypoint" },
                            [249] = { name = "Ojon\'s Lumbermill Waypoint" },
                            [250] = { name = "Beetletun Waypoint" },
                            [251] = { name = "Tunwatch Redoubt Waypoint" },
                            [252] = { name = "Godslost Waypoint" },
                            [836] = { name = "Orchard Waypoint" },
                            [837] = { name = "Scaver Waypoint" },
                    },
            },
           
            [54] = { --Brisban Wildlands
                    poi = {
                            [75] = { name = "Ogotl Grounds" },
                            [76] = { name = "Invariant Base" },
                            [77] = { name = "Joy\'s End" },
                            [78] = { name = "Beldame\'s Rise" },
                            [79] = { name = "Seraph Protectors" },
                            [80] = { name = "Willem\'s Bandits" },
                            [81] = { name = "Scotta\'s Bandits" },
                            [82] = { name = "Angelan\'s Bandits" },
                            [83] = { name = "Skrittsatawney" },
                            [84] = { name = "Enrav Exploration Post" },
                            [85] = { name = "Breean\'s Bandits" },
                            [86] = { name = "Plunder Hold" },
                            [87] = { name = "Seanan\'s Bandits" },
                            [88] = { name = "Robbari\'s Bandits" },
                            [89] = { name = "Fort Vandal" },
                            [90] = { name = "Thaumacore Inquiry Center" },
                            [91] = { name = "Revered Terebinth" },
                            [102] = { name = "Aethervolt Lab" },
                            [823] = { name = "Cutpurse Circle" },
                    },
                    waypoint = {
                            [92] = { name = "Watchful Source Waypoint" },
                            [93] = { name = "Wendon Waypoint" },
                            [94] = { name = "Tunnels Waypoint" },
                            [95] = { name = "Hillstead Waypoint" },
                            [96] = { name = "East End Waypoint" },
                            [97] = { name = "Brilitine Waypoint" },
                            [98] = { name = "Seraph Observers Waypoint" },
                            [99] = { name = "Gallowfields Waypoint" },
                            [100] = { name = "Triforge Point Waypoint" },
                            [101] = { name = "Ulta Metamagicals Waypoint" },
                            [117] = { name = "Mrot Boru Waypoint" },
                            [118] = { name = "Mirkrise Waypoint" },
                            [1785] = { name = "Proxemics Lab" },
                    },
            },
           
            [34] = { --Caledon Forest
                    poi = {
                            [103] = { name = "Solitaire Island" },
                            [104] = { name = "Caer Verdant" },
                            [105] = { name = "Golotl Grounds" },
                            [106] = { name = "Bay Haven" },
                            [107] = { name = "Morgatl Grounds" },
                            [108] = { name = "Naulshead Refuge" },
                            [109] = { name = "Stormwreck Deeps" },
                            [110] = { name = "Hemlock Coil" },
                            [111] = { name = "Hanto Trading Post" },
                            [112] = { name = "Hazupl Grounds" },
                            [113] = { name = "Soggorsort" },
                            [114] = { name = "Slaver\'s Deeps" },
                            [115] = { name = "Banshee\'s Keen" },
                            [116] = { name = "Dengatl Grounds" },
                            [1087] = { name = "Briarthorn Den" },
                            [1088] = { name = "The Weeping Isle" },
                            [1089] = { name = "Dolorous Vale" },
                            [1093] = { name = "Rime\'s Garden" },
                            [1280] = { name = "Danador\'s Kennel" },
                            [1281] = { name = "Zopatl Grounds" },
                    },
                    waypoint = {
                            [308] = { name = "Astorea Waypoint" },
                            [309] = { name = "Spiral Waypoint" },
                            [310] = { name = "Caer Astorea Waypoint" },
                            [311] = { name = "Gleaner\'s Cove Waypoint" },
                            [312] = { name = "Brigid\'s Overlook Waypoint" },
                            [313] = { name = "Sperrins Waypoint" },
                            [314] = { name = "Mabon Waypoint" },
                            [315] = { name = "Town of Cathal Waypoint" },
                            [316] = { name = "Caledon Haven Waypoint" },
                            [317] = { name = "Titan\'s Staircase Waypoint" },
                            [318] = { name = "Falias Thorpe Waypoint" },
                            [319] = { name = "Hamlet of Annwen Waypoint" },
                            [320] = { name = "Kraitbane Haven Waypoint" },
                            [321] = { name = "Wychmire Waypoint" },
                            [322] = { name = "Wardenhurst Waypoint" },
                            [844] = { name = "Lionguard Waystation Waypoint" },
                            [1345] = { name = "Twilight Arbor Waypoint" },
                            [1534] = { name = "Sleive\'s Waypoint" },
                    },
            },
           
            [35] = { --Metrica Province
                    poi = {
                            [51] = { name = "Incinergen Labs" },
                            [52] = { name = "Battleground Plaza" },
                            [53] = { name = "The Opticalium" },
                            [54] = { name = "Durotl Grounds" },
                            [55] = { name = "Aquannian Research Group" },
                            [56] = { name = "Dr. Bleent\'s Encampment" },
                            [57] = { name = "Old Oola Lab" },
                            [58] = { name = "Parnna\'s Gate" },
                            [59] = { name = "Conduit Tower Blig" },
                            [60] = { name = "Conduit Tower Nopp" },
                            [61] = { name = "Inner Inquest Complex" },
                            [62] = { name = "Transfer Gate (Private)" },
                            [63] = { name = "Conduit Tower Scoln" },
                            [141] = { name = "C.L.E.A.N. Station" },
                            [551] = { name = "PR&T Esoterics" },
                            [552] = { name = "Incomp Optics" },
                            [553] = { name = "Brill Alliance Labs" },
                            [1076] = { name = "Splorge Metamystics Lab" },
                            [1134] = { name = "Transformer Hub Kachong" },
                            [1191] = { name = "Biocauldron Alchemics" },
                            [1289] = { name = "Terranexic Lab" },
                            [1290] = { name = "Aeronotics Lab" },
                            [1535] = { name = "Old Flamen Lab" },
                    },
                    waypoint = {
                            [64] = { name = "Soren Draa Waypoint" },
                            [65] = { name = "Jeztar Falls Waypoint" },
                            [66] = { name = "Akk Wilds Waypoint" },
                            [67] = { name = "Rana Landing Complex Waypoint" },
                            [68] = { name = "Arterium Haven Waypoint" },
                            [69] = { name = "Hexane Regrade Waypoint" },
                            [70] = { name = "Survivor\'s Encampment Waypoint" },
                            [71] = { name = "Muridian Waypoint" },
                            [72] = { name = "Desider Atum Waypoint" },
                            [1198] = { name = "Old Golem Factory Waypoint" },
                            [1199] = { name = "Loch Waypoint" },
                            [1200] = { name = "Anthill Waypoint" },
                            [1201] = { name = "Michotl Grounds Waypoint" },
                            [1202] = { name = "Cuatl Waypoint" },
                            [1203] = { name = "Artergon Waypoint" },
                            [1271] = { name = "Hydrone Unit Waypoint" },
                    },
            },
           
            [39] = { --Mount Maelstrom
                    poi = {
                            [692] = { name = "Valley of Gwaun" },
                            [693] = { name = "Tzanopl Grounds" },
                            [694] = { name = "Restless Deeps" },
                            [695] = { name = "Gorlois Spine" },
                            [696] = { name = "Venomblight" },
                            [697] = { name = "Gallant\'s Folly" },
                            [698] = { name = "Evisomancer\'s Resort" },
                            [699] = { name = "Malxa Pyronetics" },
                            [700] = { name = "Moonlight Rill" },
                            [701] = { name = "Zone Violet" },
                            [702] = { name = "Zone White" },
                            [703] = { name = "Zone Green" },
                            [704] = { name = "Zone Black" },
                            [705] = { name = "Zone Red" },
                            [706] = { name = "Zone Blue (Under Construction)" },
                            [707] = { name = "Breth Ayahusasca" },
                            [708] = { name = "Rata Pten" },
                            [709] = { name = "Herot\'s Ascent" },
                            [710] = { name = "Theurgic Volute" },
                            [1677] = { name = "Aquabase Terror Seven" },
                            [1678] = { name = "New Skrittstead" },
                            [1679] = { name = "Forge Foundations" },
                            [1680] = { name = "Gloomirk Outpost" },
                            [1681] = { name = "Mosstide Walfts" },
                            [1682] = { name = "Aliyana\'s Haunt" },
                            [1683] = { name = "Treacherous Vents" },
                            [1684] = { name = "Maelstrom\'s Core" },
                            [1685] = { name = "Hellmouth Falls" },
                            [1686] = { name = "Felsic Plains" },
                            [1687] = { name = "Clandest Basecamp" },
                            [1688] = { name = "Lonatl Grounds" },
                            [1689] = { name = "Observation Platform XKV" },
                    },
                    waypoint = {
                            [711] = { name = "Murkvale Waypoint" },
                            [712] = { name = "Govoran Waypoint" },
                            [713] = { name = "Criterion Waypoint" },
                            [714] = { name = "Firebreak Fort Waypoint" },
                            [715] = { name = "Spaecia Illogica Waypoint" },
                            [716] = { name = "Bard\'s Waypoint" },
                            [717] = { name = "Maelstrom\'s Waypoint" },
                            [718] = { name = "Ashen Waypoint" },
                            [719] = { name = "Avernan Waypoint" },
                            [720] = { name = "Broken Arrow Waypoint" },
                            [721] = { name = "Oxbow Isle Waypoint" },
                            [722] = { name = "Irwin Isle Waypoint" },
                            [723] = { name = "Gauntlet Waypoint" },
                            [724] = { name = "Old Sledge Site Waypoint" },
                            [725] = { name = "Judgement Waypoint" },
                            [726] = { name = "Magmatic Waypoint" },
                            [1346] = { name = "Crucible of Eternity Waypoint" },
                    },
            },
           
            [53] = { --Sparkfly Fen
                    poi = {
                            [433] = { name = "Deadman\'s Reach" },
                            [434] = { name = "Porgotl Grounds" },
                            [435] = { name = "Occuintl Grounds" },
                            [436] = { name = "Nicantl Grounds" },
                            [437] = { name = "The Tower of Modius" },
                            [438] = { name = "Quinatl Deadgrounds" },
                            [439] = { name = "Sunken Chaladeen" },
                            [440] = { name = "Jinotl Deadgrounds" },
                            [441] = { name = "Brokenhope Village" },
                            [442] = { name = "Shrine of Usharr" },
                            [443] = { name = "Inquest Hexfoundry G-14" },
                            [444] = { name = "Ruined Vallah" },
                            [445] = { name = "United Arcanist Lab" },
                            [446] = { name = "Fabled Djannor" },
                            [447] = { name = "Wrathwave Depths" },
                            [448] = { name = "Wreck of the Argent Warrior" },
                            [449] = { name = "Shorewatch Post" },
                            [450] = { name = "Swampwatch Post" },
                            [451] = { name = "Southwatch Post" },
                            [945] = { name = "Battlement Shore" },
                    },
                    waypoint = {
                            [452] = { name = "Orvar\'s Glen Waypoint" },
                            [453] = { name = "Fort Cadence Waypoint" },
                            [454] = { name = "Braggi\'s Stead Waypoint" },
                            [455] = { name = "Saltflood Waypoint" },
                            [456] = { name = "Zintl Holy Grounds Waypoint" },
                            [457] = { name = "Ocean\'s Gullet Waypoint" },
                            [458] = { name = "Forvar\'s Waypoint" },
                            [459] = { name = "Toade\'s Head Waypoint" },
                            [460] = { name = "Flamefrog Waypoint" },
                            [461] = { name = "Darkweather Waypoint" },
                            [462] = { name = "Brackwater Waypoint" },
                            [463] = { name = "Aleem\'s Waypoint" },
                            [464] = { name = "Splintered Coast Waypoint" },
                            [465] = { name = "Brooloonu Waypoint" },
                            [845] = { name = "Dryground Waypoint" },
                            [947] = { name = "Caer Brier Waypoint" },
                            [948] = { name = "Mire Waypoint" },
                    },
            },
           
            [62] = { --Cursed Shore
                    poi = {
                            [764] = { name = "Bitter Mountain" },
                            [765] = { name = "Caer Shadowfain" },
                            [766] = { name = "Village Sayix" },
                            [767] = { name = "Seachange Tidepools" },
                            [768] = { name = "Cachistic R&D" },
                            [769] = { name = "Gavebeorn\'s Landing" },
                            [770] = { name = "Bakkir Sarayi" },
                            [771] = { name = "Winterknell Labyrinth" },
                            [772] = { name = "Shelter\'s Gate" },
                            [773] = { name = "Gallow\'s Hang" },
                            [774] = { name = "Village of Ewan" },
                            [775] = { name = "Thorn Dock" },
                            [776] = { name = "The Wreck of the Golden Vanity" },
                            [777] = { name = "Harbinger Torch" },
                            [778] = { name = "Death\'s Gaze Torch" },
                            [779] = { name = "Buried Archives" },
                            [780] = { name = "Altar of Murdered Dreams" },
                            [781] = { name = "Death\'s Anthem" },
                            [782] = { name = "The Wreck of Saehrimnir" },
                            [783] = { name = "Meddler\'s Summit" },
                            [784] = { name = "Telmat Knoll" },
                            [785] = { name = "Augur\'s Torch" },
                            [786] = { name = "Shank Anchorage" },
                            [787] = { name = "Sharn\'s Free Camp" },
                            [788] = { name = "Reliquary Vault" },
                            [789] = { name = "Gates of Arah" },
                            [790] = { name = "Altar of the Withered Heart" },
                            [1260] = { name = "Jofast\'s Camp" },
                    },
                    waypoint = {
                            [791] = { name = "Pursuit Pass Waypoint" },
                            [792] = { name = "R&D Waypoint" },
                            [793] = { name = "Penitent Waypoint" },
                            [794] = { name = "Gavbeorn\'s Waypoint" },
                            [795] = { name = "Verdance Waypoint" },
                            [796] = { name = "Shelter\'s Gate Waypoint" },
                            [797] = { name = "Jofast\'s Waypoint" },
                            [798] = { name = "Meddler\'s Waypoint" },
                            [799] = { name = "Anchorage Waypoint" },
                            [800] = { name = "Arah Waypoint" },
                            [801] = { name = "Caer Shadowfain Waypoint" },
                            [802] = { name = "Murdered Dreams Waypoint" },
                            [1764] = { name = "Shipwreck Rock Waypoint" },
                    },
            },
           
            [65] = { --Malchor\'s Leap
                    poi = {
                            [647] = { name = "Pagga\'s Post" },
                            [648] = { name = "Shark\'s Tooth Isle" },
                            [649] = { name = "Eastern Colonnade" },
                            [650] = { name = "Beacon Torch" },
                            [651] = { name = "Plaza of Lights" },
                            [652] = { name = "Altar of Tempests" },
                            [653] = { name = "Alarjann Bayt" },
                            [654] = { name = "The Wealdwood" },
                            [655] = { name = "Kitah Manse" },
                            [656] = { name = "Upsilon Test Facility" },
                            [657] = { name = "Sculptor\'s End" },
                            [658] = { name = "Omicron Test Facility" },
                            [659] = { name = "Arcadian Deeps" },
                            [660] = { name = "Altar of Lies" },
                            [661] = { name = "Spark of Ilya" },
                            [662] = { name = "Song of Lyss" },
                            [663] = { name = "Seal of Union" },
                            [664] = { name = "Malchor\'s Anguish" },
                            [665] = { name = "Mirror\'s Handle" },
                            [666] = { name = "Murmur Isle" },
                            [667] = { name = "Shelter Docks" },
                            [668] = { name = "Doric\'s Shrine" },
                            [669] = { name = "Kahloipoi Village" },
                            [670] = { name = "Rayhan Bayt" },
                            [671] = { name = "Bayt Fallahin" },
                            [672] = { name = "Saliah Bayt" },
                            [673] = { name = "Wreck of the Qashvian" },
                            [674] = { name = "Follower\'s Bridge" },
                            [675] = { name = "Dhuum\'s Last Stand" },
                            [676] = { name = "Village of Wren" },
                            [677] = { name = "Hope Falls" },
                            [1259] = { name = "Augur\'s Grotto" },
                            [1273] = { name = "Harbinger" },
                            [1277] = { name = "Versoconjouring Array" },
                            [1622] = { name = "Bauxite Alchemicals" },
                            [1623] = { name = "King\'s Passage" },
                            [1690] = { name = "Reflection Cove" },
                    },
                    waypoint = {
                            [678] = { name = "Pagga\'s Waypoint" },
                            [679] = { name = "Doric\'s Waypoint" },
                            [680] = { name = "Waste Hollows Waypoint" },
                            [681] = { name = "Colonnade Waypoint" },
                            [682] = { name = "Valley of Lyss Waypoint" },
                            [683] = { name = "Union Waypoint" },
                            [684] = { name = "Wren Waypoint" },
                            [685] = { name = "Lyssa Waypoint" },
                            [686] = { name = "Blighted Arch Waypoint" },
                            [687] = { name = "Murmur Waypoint" },
                            [688] = { name = "Tempests Waypoint" },
                            [689] = { name = "Versoconjouring Waypoint" },
                            [690] = { name = "Lights Waypoint" },
                    },
            },
           
            [51] = { --Straits of Devastation
                    poi = {
                            [727] = { name = "Oceanside Ordnance" },
                            [728] = { name = "Razorslide Bivouac" },
                            [729] = { name = "Stentor Cannonade" },
                            [730] = { name = "Thunderhead Battery" },
                            [731] = { name = "Cadrigan\'s Jetty" },
                            [732] = { name = "Izz-al-Din Sarayi" },
                            [733] = { name = "Broken Spit" },
                            [734] = { name = "The Vizier\'s Tower" },
                            [735] = { name = "Stygian Deeps" },
                            [736] = { name = "Plaza of Lost Wisdom" },
                            [737] = { name = "Lone Post" },
                            [738] = { name = "Conquest Marina" },
                            [739] = { name = "Brassclaw Landing" },
                            [740] = { name = "Snipe Hill" },
                            [741] = { name = "Altar of Betrayal" },
                            [742] = { name = "Compass Bridge" },
                            [743] = { name = "Din al-Jindi" },
                            [744] = { name = "Chapel of Lady Glaive" },
                            [745] = { name = "The Royal Forum" },
                            [746] = { name = "The Vesper Bell" },
                            [747] = { name = "Monastery of Tughra" },
                            [816] = { name = "Zaishen Antheneum" },
                            [1021] = { name = "Armada Harbor" },
                            [1022] = { name = "Alseta Generator" },
                            [1023] = { name = "Caer Aval" },
                            [1230] = { name = "Lasciate Gateway" },
                            [1231] = { name = "Brassburn Torch" },
                            [1232] = { name = "Pact Rally Waypoint" },
                            [1233] = { name = "Conservatory" },
                            [1626] = { name = "The Underbelly" },
                    },
                    waypoint = {
                            [748] = { name = "Bramble Pass Waypoint" },
                            [749] = { name = "Signal Peak Waypoint" },
                            [750] = { name = "Fort Trinity Waypoint" },
                            [751] = { name = "Thorn Pass Waypoint" },
                            [752] = { name = "Thunderhead Waypoint" },
                            [753] = { name = "Broken Spit Waypoint" },
                            [754] = { name = "Vesper Bell Waypoint" },
                            [755] = { name = "Royal Forum Waypoint" },
                            [756] = { name = "Brassclaw Waypoint" },
                            [757] = { name = "Tughra Waypoint" },
                            [758] = { name = "Conquest Marina Waypoint" },
                            [759] = { name = "Lone Post Waypoint" },
                            [760] = { name = "Waywarde Waypoint" },
                            [761] = { name = "Xenarius Waypoint" },
                            [762] = { name = "Glorious Victory Waypoint" },
                            [763] = { name = "Sentry Waypoint" },
                            [1234] = { name = "Rally Waypoint" },
                            [1624] = { name = "Plinth Timberland Waypoint" },
                            [1625] = { name = "Underbelly Waypoint" },
                            [1765] = { name = "Dire Shoal Waypoint" },
                    },
            },
           
            [873] = { --Southsun Cove
                    poi = {
                            [1748] = { name = "Onyx Field" },
                            [1750] = { name = "Privateer\'s Moorage" },
                            [1753] = { name = "Ember Passage" },
                            [1754] = { name = "Canach\'s Folly" },
                            [1755] = { name = "Karka Hive" },
                    },
                    waypoint = {
                            [1744] = { name = "Lion Point Waypoint" },
                            [1746] = { name = "Pride Point Waypoint" },
                            [1749] = { name = "Pearl Islet Waypoint" },
                            [1751] = { name = "Camp Karka Waypoint" },
                            [1752] = { name = "Owain\'s Refuge Waypoint" },
                            [1756] = { name = "Kiel\'s Outpost Waypoint" },
                    },
            },
           
            [26] = { --Dredgehaunt Cliffs
                    poi = {
                            [554] = { name = "Leaning Grade" },
                            [555] = { name = "Fridgardr Lodge" },
                            [556] = { name = "Mantelet Refuge" },
                            [557] = { name = "Esjudare Scratch" },
                            [558] = { name = "Shelter Pointe" },
                            [559] = { name = "Vpered Drill" },
                            [560] = { name = "Theign Kenning" },
                            [561] = { name = "Landslide Lee" },
                            [562] = { name = "Travelen\'s Steading" },
                            [563] = { name = "Bergtrolde" },
                            [564] = { name = "Skovtrolde Hearthstead" },
                            [565] = { name = "Talecrafting Steading" },
                            [566] = { name = "The Speaking Place" },
                            [1266] = { name = "Firebase Molek" },
                            [1267] = { name = "Tomb of Morlog" },
                            [1268] = { name = "Tomb of Blackpowder" },
                            [1269] = { name = "Tomb of Stoneskin" },
                            [1291] = { name = "Brandalf\'s Steading" },
                            [1486] = { name = "Falooaloo" },
                            [1577] = { name = "Bear\'s Jaws Shrine" },
                            [1578] = { name = "Leopard\'s Snarl Shrine" },
                            [1579] = { name = "Raven\'s Wing Shrine" },
                            [1580] = { name = "Wolf\'s Lair Shrine" },
                            [1700] = { name = "Ghost Stones" },
                    },
                    waypoint = {
                            [598] = { name = "Tribulation Waypoint" },
                            [599] = { name = "Frostland Waypoint" },
                            [600] = { name = "Dociu Waypoint" },
                            [601] = { name = "Seven Pines Waypoint" },
                            [602] = { name = "Grey Road Waypoint" },
                            [603] = { name = "Steelbrachen Waypoint" },
                            [604] = { name = "Toran Hollow Waypoint" },
                            [605] = { name = "Hessdallen Kenning Waypoint " },
                            [606] = { name = "Kenning Testing Ground" },
                            [607] = { name = "Wide Expanse Waypoint" },
                            [608] = { name = "Nottowr Fault Waypoint" },
                            [609] = { name = "Mountain\'s Tail Waypoint" },
                            [610] = { name = "Graupel Waypoint" },
                            [611] = { name = "Havfrue Basin Waypoint" },
                            [612] = { name = "Travelen\'s Waypoint" },
                            [613] = { name = "Wyrmblood Waypoint" },
                            [1262] = { name = "Granite Citadel Waypoint" },
                            [1343] = { name = "Sorrow\'s Embrace Waypoint" },
                    },
            },
           
            [30] = { --Frostgorge Sound
                    poi = {
                            [618] = { name = "The Sonic Furnace" },
                            [619] = { name = "Forgepits" },
                            [620] = { name = "Arkor\'s Tomb" },
                            [621] = { name = "Krok\'s Ruin" },
                            [622] = { name = "Sacred Trust" },
                            [623] = { name = "Elder\'s Vale" },
                            [624] = { name = "Safewatch Vale" },
                            [625] = { name = "Orsippus" },
                            [626] = { name = "Moshpoipoi" },
                            [627] = { name = "Zuckermaloo" },
                            [628] = { name = "Deep and Troubled Waters" },
                            [629] = { name = "The Barrowstead" },
                            [630] = { name = "Coiled Watch" },
                            [631] = { name = "Claw Watch" },
                            [841] = { name = "Firesnake\'s Tail" },
                            [842] = { name = "Offering Stone" },
                            [1261] = { name = "Ridgepost Sentry" },
                            [1511] = { name = "Iron Horse Mines" },
                            [1588] = { name = "Peloopoo Needle" },
                            [1701] = { name = "Blue Ice Station" },
                    },
                    waypoint = {
                            [632] = { name = "Arundon Waypoint" },
                            [633] = { name = "Groznev Waypoint" },
                            [634] = { name = "Earthshake Waypoint" },
                            [635] = { name = "Path of Starry Skies Waypoint" },
                            [636] = { name = "Slough of Despond Waypoint" },
                            [637] = { name = "Watchful Waypoint" },
                            [638] = { name = "Ice Floe Waypoint" },
                            [639] = { name = "Dimotiki Waypoint" },
                            [640] = { name = "Twoloop Waypoint" },
                            [641] = { name = "Skyheight Steading Waypoint" },
                            [642] = { name = "Highpeaks Waypoint" },
                            [643] = { name = "Ridgerock Camp Waypoint" },
                            [644] = { name = "Yak\'s Bend Waypoint" },
                            [645] = { name = "Blue Ice Shining Waypoint" },
                            [646] = { name = "Drakkar Waypoint" },
                            [1347] = { name = "Honor of the Waves Waypoint" },
                    },
            },
           
            [27] = { --Lornar\'s Pass
                    poi = {
                            [280] = { name = "Ettinworks Lab" },
                            [281] = { name = "Black Barl\'s Mill" },
                            [282] = { name = "Pinion Pass" },
                            [283] = { name = "The Molitage Digs" },
                            [284] = { name = "Cascade Bridge" },
                            [285] = { name = "Greybeard\'s Landing" },
                            [286] = { name = "Jetsam Isle" },
                            [287] = { name = "Koolookuu" },
                            [288] = { name = "Olia\'s Clearing" },
                            [289] = { name = "Afgar\'s Steading" },
                            [290] = { name = "Grenth\'s Door" },
                            [291] = { name = "Icebound Plunge" },
                            [292] = { name = "Molevon Portage" },
                            [293] = { name = "Priory Archives" },
                            [294] = { name = "Ogden\'s Quarters" },
                            [295] = { name = "The Dracon Steles" },
                            [296] = { name = "Ironhammer\'s Crypt" },
                            [297] = { name = "Korakatt\'s Hall" },
                            [298] = { name = "Nentor\'s Consolidated Mine" },
                            [299] = { name = "Belldron\'s Guardholme" },
                            [1221] = { name = "Windy Cave" },
                            [1293] = { name = "Lyot\'s Herd" },
                            [1598] = { name = "Skritt Hill" },
                            [1599] = { name = "Glorious Dredge Excavation #74" },
                            [1600] = { name = "Lost Owl Shrine" },
                            [1601] = { name = "Ravenbeak Shrine" },
                            [1602] = { name = "Bearstone Shrine" },
                            [1603] = { name = "Wolfpaw Shrine" },
                            [1604] = { name = "Leopardshadow Shrine" },
                            [1605] = { name = "The Riven Path" },
                            [1606] = { name = "Keddle Morraine" },
                            [1607] = { name = "Priory Bridge" },
                            [1608] = { name = "Steam Mechagate" },
                            [1609] = { name = "Maw\'s Rise" },
                            [1610] = { name = "Skylady\'s Memory" },
                            [1611] = { name = "Mette\'s Posting" },
                            [1612] = { name = "Dwarves\' Gloaming" },
                            [1613] = { name = "Grogshadow Kenning" },
                            [1614] = { name = "Guutra\'s Secret" },
                            [1615] = { name = "Twoheaded Meadows" },
                            [1616] = { name = "Wonderous Drill Installation #73" },
                            [1628] = { name = "Posternus Caverns" },
                            [1629] = { name = "Rocklair" },
                    },
                    waypoint = {
                            [229] = { name = "Vanjir\'s Stead Waypoint" },
                            [230] = { name = "Demon\'s Maw Waypoint" },
                            [231] = { name = "Winterthaw Waypoint" },
                            [232] = { name = "False Lake Waypoint" },
                            [233] = { name = "Durmand Priory Waypoint" },
                            [234] = { name = "Lamentation Waypoint" },
                            [235] = { name = "Thunderhorns Waypoint" },
                            [236] = { name = "Nentor Waypoint" },
                            [406] = { name = "Guutra\'s Homestead Waypoint" },
                            [407] = { name = "Stonescatter Waypoint" },
                            [408] = { name = "Pinnacle Enclave Waypoint" },
                            [409] = { name = "Mistriven Waypoint" },
                            [1617] = { name = "Icedevil\'s Waypoint" },
                            [1618] = { name = "Refuge Peak Waypoint" },
                            [1619] = { name = "Afgar\'s Waypoint" },
                            [1620] = { name = "Cascade Bridge Waypoint" },
                    },
            },
           
            [31] = { --Snowden Drifts
                    poi = {
                            [142] = { name = "Drakentelt" },
                            [143] = { name = "Svannijem Hold" },
                            [144] = { name = "Urgulp" },
                            [145] = { name = "Tala Point" },
                            [146] = { name = "Lashoosh" },
                            [147] = { name = "Durgar\'s Homestead" },
                            [163] = { name = "Owl Lodge" },
                            [164] = { name = "Blasted Haven" },
                            [824] = { name = "Mennerheim" },
                            [1034] = { name = "Moldary Point" },
                            [1597] = { name = "Jorand\'s Sluice" },
                    },
                    waypoint = {
                            [179] = { name = "Skradden Waypoint" },
                            [180] = { name = "Lornar\'s Waypoint" },
                            [181] = { name = "Highpass Haven Waypoint" },
                            [182] = { name = "Lost Child\'s Sorrow Waypoint" },
                            [183] = { name = "Scholar\'s Waypoint" },
                            [184] = { name = "Isenfall Waypoint" },
                            [185] = { name = "Snowdrift Waypoint" },
                            [186] = { name = "Seraph Outriders\' Waypoint" },
                            [187] = { name = "Torstvedt Homestead Waypoint " },
                            [188] = { name = "Exile Waypoint" },
                            [189] = { name = "Njordstead Waypoint" },
                            [190] = { name = "Soderhem Steading Waypoint" },
                            [191] = { name = "Snowhawk Landing Waypoint" },
                            [192] = { name = "Reaver\'s Waypoint" },
                            [193] = { name = "Owl Waypoint" },
                            [194] = { name = "Podaga Steading Waypoint" },
                            [959] = { name = "Frozen Sweeps Waypoint" },
                            [960] = { name = "Valslake Waypoint" },
                            [1791] = { name = "Angvar\'s Trove Waypoint" },
                    },
            },
           
            [29] = { --Timberline Falls
                    poi = {
                            [567] = { name = "Caer Evermore" },
                            [568] = { name = "Okarinoo" },
                            [569] = { name = "Irenic Shoal" },
                            [570] = { name = "Sipedon Deeps" },
                            [571] = { name = "Kiriel Rock" },
                            [572] = { name = "The Great Oouo" },
                            [573] = { name = "Whispering Falls" },
                            [574] = { name = "Stovepipe Pogue" },
                            [575] = { name = "Goldenlight Hallow" },
                            [576] = { name = "Thistlereed Grove" },
                            [577] = { name = "Kyesjard" },
                            [578] = { name = "Balddistead" },
                            [579] = { name = "Copperhammer Mines" },
                    },
                    waypoint = {
                            [580] = { name = "Talus Waypoint" },
                            [581] = { name = "Serpent Waypoint" },
                            [582] = { name = "Okarinoo Waypoint" },
                            [583] = { name = "Coil Waypoint" },
                            [584] = { name = "Scale Strand Waypoint" },
                            [585] = { name = "Nonmoa Waypoint" },
                            [586] = { name = "Eztlitl Grounds Waypoint" },
                            [587] = { name = "Gyre Rapids Waypoint" },
                            [588] = { name = "Valance Tutory Waypoint" },
                            [589] = { name = "Ogduk Waypoint" },
                            [590] = { name = "Foundation 86 Waypoint" },
                            [591] = { name = "White Paper Waypoint" },
                            [592] = { name = "Gentle River Waypoint" },
                            [593] = { name = "Thistlereed Waypoint" },
                            [594] = { name = "Krongar Waypoint" },
                            [595] = { name = "Iron Veil Waypoint" },
                            [596] = { name = "Rankor Ruins Waypoint" },
                            [597] = { name = "Concordia Waypoint" },
                            [1094] = { name = "Stromkarl Waypoint" },
                    },
            },
           
            [28] = { --Wayfarer Foothills
                    poi = {
                            [357] = { name = "Heart of the Wolf" },
                            [358] = { name = "Hirbadd\'s Camp" },
                            [359] = { name = "Drakkerjorg Pit" },
                            [360] = { name = "Hostra\'s Refuge" },
                            [361] = { name = "Heart of the Bear" },
                            [362] = { name = "Heart of the Raven" },
                            [363] = { name = "Heart of the Snow Leopard" },
                            [364] = { name = "Alpenzure Cave" },
                            [365] = { name = "Gaerta\'s Summit" },
                            [366] = { name = "Hermit\'s Watch" },
                            [367] = { name = "Victor\'s Point" },
                            [368] = { name = "Edenvar\'s Homestead" },
                            [369] = { name = "Kevach\'s Homestead" },
                            [974] = { name = "Haivoissen Kenning" },
                            [975] = { name = "Dragonblest Hold" },
                            [976] = { name = "Frostcreek Steading" },
                            [984] = { name = "The Frozen Maw" },
                            [1032] = { name = "Warmspring Grotto" },
                            [1691] = { name = "Heart of Corruption" },
                            [1792] = { name = "Rugnar\'s Steading" },
                    },
                    waypoint = {
                            [370] = { name = "Outcast\'s Waypoint" },
                            [371] = { name = "Hero\'s Moot Waypoint" },
                            [372] = { name = "Horncall Waypoint" },
                            [373] = { name = "Darkriven Waypoint" },
                            [374] = { name = "Taigan Waypoint" },
                            [375] = { name = "Zelechor Hot Springs Waypoint" },
                            [376] = { name = "Halvaunt Waypoint" },
                            [377] = { name = "Crossroads Haven Waypoint" },
                            [378] = { name = "Dawnrise Waypoint " },
                            [379] = { name = "Dolyak Pass Waypoint" },
                            [380] = { name = "Solitude Waypoint " },
                            [381] = { name = "Twinspur Haven Waypoint" },
                            [382] = { name = "Vendrake\'s Homestead Waypoint" },
                            [961] = { name = "Lostvyrm Cave Waypoint" },
                            [962] = { name = "Krennak\'s Homestead" },
                            [963] = { name = "Grawlenfjord Waypoint" },
                            [1025] = { name = "Osenfold Waypoint " },
                    },
            },
                   
            --*************************************************************************************************************
            -- WVW
            --*************************************************************************************************************
           
            [38] = { --Eternal Battlegrounds
                    poi = {
                            [990] = { name = "Stonemist Keep" },
                            [991] = { name = "Great Northern Gate" },
                            [992] = { name = "Great Eastern Gate" },
                            [993] = { name = "Great Western Gate" },
                            [994] = { name = "Blue World Keep" },
                            [995] = { name = "Durios Post" },
                            [996] = { name = "Umberglade Mill" },
                            [997] = { name = "Langor Tower" },
                            [998] = { name = "Bravost Tower" },
                            [999] = { name = "Danelon Mine" },
                            [1000] = { name = "Quentin Post" },
                            [1001] = { name = "Dragoss Kraal" },
                            [1002] = { name = "Novotl Grounds" },
                            [1003] = { name = "Red World Keep" },
                            [1004] = { name = "Anzalias Post" },
                            [1005] = { name = "Speldan Mill" },
                            [1006] = { name = "Veloka Tower" },
                            [1007] = { name = "Mendon\'s Tower" },
                            [1008] = { name = "Pangloss Mine" },
                            [1009] = { name = "Ogrewatch Post" },
                            [1010] = { name = "Molevek Works" },
                            [1011] = { name = "Green World Keep" },
                            [1012] = { name = "Klovan Post" },
                            [1013] = { name = "Golanta Mill" },
                            [1014] = { name = "Jerrifer\'s Tower" },
                            [1015] = { name = "Aldon\'s Tower" },
                            [1016] = { name = "Hooligan\'s Mine" },
                            [1017] = { name = "Wildcreek Post" },
                    },
                    waypoint = {
                            [1018] = { name = "Blue World Hill Waypoint" },
                            [1019] = { name = "Red World Hill Waypoint" },
                            [1020] = { name = "Green World Hill Waypoint" },
                            [1213] = { name = "Stonemist Waypoint" },
                            [1214] = { name = "Overlook Waypoint" },
                            [1215] = { name = "Valley Waypoint" },
                            [1216] = { name = "Lowlands Waypoint" },
                    },
            },
                   
            [96] = { --Blue Borderlands
                    poi = {
                            [1311] = { name = "Spiritholme Crossroads" },
                            [1312] = { name = "Askalion Bastion" },
                            [1313] = { name = "Stargrove Mill" },
                            [1314] = { name = "Temple of Thunder" },
                            [1315] = { name = "Brownmane Camp" },
                            [1316] = { name = "Blue World Bastion" },
                            [1317] = { name = "Champion\'s Orchard" },
                            [1318] = { name = "Greenwater Village" },
                            [1319] = { name = "Chitterogg Camp" },
                            [1320] = { name = "Ascension Bastion" },
                            [1321] = { name = "Godslore Quarry" },
                            [1322] = { name = "Redbriar Tower" },
                            [1323] = { name = "Greenlake Tower" },
                            [1324] = { name = "Woodhaven Tower" },
                            [1325] = { name = "Dawn\'s Tower" },
                            [1326] = { name = "Redvale Workshop" },
                    },
                    waypoint = {
                            [1235] = { name = "Ascension Bay Waypoint" },
                            [1236] = { name = "<sup>Green</sup>Border Waypoint" },
                            [1237] = { name = "Garrison Waypoint" },
                            [1238] = { name = "<sup>Red</sup>Border Waypoint" },
                            [1239] = { name = "Askalion Hills Waypoint" },
                            [1240] = { name = "Citadel Waypoint" },
                    },
            },
                   
            [95] = { --Green Borderlands
                    poi = {
                            [1327] = { name = "Dreadfall Bastion" },
                            [1328] = { name = "Shadaran Bastion" },
                            [1329] = { name = "Spiritholme Crossroads" },
                            [1330] = { name = "Green World Bastion" },
                            [1331] = { name = "Foghaven Mill" },
                            [1332] = { name = "Temple of Lightning" },
                            [1333] = { name = "Eboneigh Camp" },
                            [1334] = { name = "Sunnyhill Tower" },
                            [1335] = { name = "Cragtop Tower" },
                            [1336] = { name = "Bluevale Workshop" },
                            [1337] = { name = "Hero\'s Orchard" },
                            [1338] = { name = "Redwater Village" },
                            [1339] = { name = "Neuskrittia Camp" },
                            [1340] = { name = "Faithleap Quarry" },
                            [1341] = { name = "Bluebriar Tower" },
                            [1342] = { name = "Redlake Tower" },
                    },
                    waypoint = {
                            [1241] = { name = "Dreadfall Bay Waypoint" },
                            [1242] = { name = "Citadel Waypoint" },
                            [1243] = { name = "Garrison Waypoint" },
                            [1244] = { name = "<sup>Red</sup>Border Waypoint" },
                            [1245] = { name = "Shadaran Hills Waypoint" },
                            [1246] = { name = "<sup>Blue</sup>Border Waypoint" },
                    },
            },
                   
            [94] = { --Red Borderlands
                    poi = {
                            [1295] = { name = "Etheron Bastion" },
                            [1296] = { name = "Temple of Storms" },
                            [1297] = { name = "Blackwicker Camp" },
                            [1298] = { name = "Godsword Crossroads" },
                            [1299] = { name = "Dreaming Bastion" },
                            [1300] = { name = "Astralholme Mill" },
                            [1301] = { name = "Chitaritta Camp" },
                            [1302] = { name = "Red World Bastion" },
                            [1303] = { name = "Bluewater Village" },
                            [1304] = { name = "Victor\'s Orchard" },
                            [1305] = { name = "Bluelake Tower" },
                            [1306] = { name = "Longview Tower" },
                            [1307] = { name = "Cliffside Tower" },
                            [1308] = { name = "Greenvale Workshop" },
                            [1309] = { name = "Arah\'s Quarry" },
                            [1310] = { name = "Greenbriar Tower" },
                    },
                    waypoint = {
                            [1223] = { name = "<sup>Green</sup>Border Waypoint" },
                            [1224] = { name = "Dreaming Bay Waypoint" },
                            [1225] = { name = "<sup>Blue</sup>Border Waypoint" },
                            [1226] = { name = "Etheron Hills Waypoint" },
                            [1227] = { name = "Garrison Waypoint" },
                            [1228] = { name = "Citadel Waypoint" },
                    },
            },
    }

